import type { GuideContent, GuideFAQ, GuideSection } from './guideContent';

function article(slug: string, headline: string, description: string, intro: string, sections: GuideSection[], faqs: GuideFAQ[], summary: string): GuideContent {
  return {
    intro, sections, faqs, summary,
    schema: { '@context': 'https://schema.org', '@type': 'Article', headline, description, author: { '@type': 'Organization', name: 'Navorika' }, datePublished: slug.startsWith('new-') ? '2026-08-29' : '2026-08-01', dateModified: '2026-08-29' },
  };
}

export const gscGuideContent: Record<string, GuideContent> = {
  'house-construction-cost-guide': article('new-house', 'How to Estimate House Construction Cost', 'A scope-first method for estimating house construction cost.',
    'A house construction cost estimate starts with a defined scope, measured built-up area, and current local rates. A cost-per-area result is useful for early feasibility, but it is not a bill of quantities, contractor quotation, or substitute for a quantity surveyor. The useful question is not only “what is the price per square foot?” but “what work, quality, location, and risk does that rate include?”', [
      { title: 'Start with built-up area and a defined scope', content: 'For an early area-based estimate:\n\nBase construction cost = total built-up area × construction rate per unit area\n\nUse the same unit on both sides: square feet with cost per square foot, or square metres with cost per square metre. Total built-up area normally includes the floor area of every included level; it is not automatically the plot area, carpet area, or a planning-authority measurement. Record whether balconies, garages, basements, external works, services, professional fees, permits, and land are included. Two rates cannot be compared fairly when their scopes differ.' },
      { title: 'Separate structure, services, and finishes', content: 'A transparent estimate groups work rather than hiding everything inside one rate. Typical groups include site preparation and foundations; structural frame or load-bearing work; walls and roofing; plumbing and electrical services; doors and windows; plastering and waterproofing; flooring, painting, fixtures, and other finishes. Material and labour costs should be visible where possible. Specification level matters: structural safety requirements are not optional “quality upgrades,” while finish selections can change cost substantially without changing floor area.' },
      { title: 'Location, procurement, wastage, and contractor margin', content: 'Labour availability, transport distance, access, soil conditions, climate, codes, permit processes, and supplier competition make construction costs local. Material wastage should be based on the material and installation method rather than one blanket percentage. Contractor overhead and margin pay for supervision, administration, equipment, insurance, risk, and profit; they should not be confused with contingency. Obtain current written supplier and contractor quotations instead of treating an online price as a local market rate.' },
      { title: 'Contingency and a worked planning example', content: 'Suppose a two-level house has 1,800 ft² of total built-up area and the user enters an illustrative rate of 150 currency units per ft². Base cost is 1,800 × 150 = 270,000. If clearly scoped site and soft costs total 22,000, the subtotal is 292,000. An illustrative 8% contingency applied to that subtotal is 23,360, producing an early planning total of 315,360 before any excluded land or financing cost. These numbers demonstrate the method only; they are not current prices or a recommendation for any region.' },
      { title: 'How to use the House Construction Cost Calculator', content: 'Enter the measured floor area, number of floors as the tool defines it, and a current custom construction rate. Add only site costs, professional or soft costs, contingency, and land cost that belong in your chosen scope. Review the result, then run low, middle, and high scenarios. Use the Construction Cost Calculator for a broader component view and the Construction Estimate Builder when you have actual quantities and line-item rates. Confirm the final scope, quantities, structural design, taxes, and contract terms with qualified local professionals.' },
      { title: 'Common estimating mistakes', content: 'Common errors include multiplying plot area instead of built-up area; counting some floors twice; comparing inclusive and exclusive rates; omitting services or external work; applying contingency to land unintentionally; using outdated rates; and adding wastage, overhead, markup, and contingency more than once. Keep an assumptions sheet beside every estimate so a later revision explains what changed.' },
    ], [
      { question: 'Is cost per square foot enough for a final budget?', answer: 'No. It is an early benchmark. A final budget needs project drawings, quantities, specifications, local rates, risk allowances, and a defined procurement scope.' },
      { question: 'Should land be included in construction cost?', answer: 'Usually it is shown separately so building cost can be compared consistently, but reporting conventions vary. Label it explicitly.' },
      { question: 'Are contingency and contractor margin the same?', answer: 'No. Contingency covers defined uncertainty; contractor margin is part of the contractor’s commercial price. Avoid double-counting either.' },
      { question: 'Does the calculator replace a contractor quotation?', answer: 'No. It organizes user-entered assumptions for early planning and cannot inspect the site or price a complete local scope.' },
    ], 'Use area-based cost as a transparent first scenario, then replace broad assumptions with measured quantities, written specifications, and current local quotations.'),

  'water-tank-size-capacity-guide': article('new-water', 'Water Tank Size & Capacity Calculation Guide', 'Calculate theoretical and usable tank volume safely.',
    'Tank sizing has two distinct parts: calculating geometric volume and deciding how much usable storage a household or project needs. A water tank calculator can solve the first part from dimensions. It cannot decide structural adequacy, water quality, pressure, fire-storage rules, or the correct reserve for a particular property.', [
      { title: 'Rectangular tank capacity formula', content: 'For a rectangular tank:\n\nVolume = internal length × internal width × internal liquid height\n\nIf all measurements are in metres, the result is cubic metres. Multiply cubic metres by 1,000 for litres. Example: an internal tank measuring 2.0 m × 1.5 m × 1.2 m has a theoretical volume of 3.6 m³, or 3,600 L. Measure internal dimensions: using external dimensions overstates capacity by the volume of walls, insulation, and fittings.' },
      { title: 'Cylindrical tank capacity formula', content: 'For a vertical cylinder:\n\nVolume = π × radius² × liquid height\n\nRadius is half the internal diameter. A cylindrical tank with 1.2 m internal diameter and 1.5 m liquid height has radius 0.6 m, so volume is π × 0.6² × 1.5 ≈ 1.696 m³, or about 1,696 L. For a horizontal cylinder that is partly full, the simple formula is not enough; segment geometry is required.' },
      { title: 'Litres, gallons, and cubic units', content: 'Useful conversions are 1 m³ = 1,000 L and 1 ft³ = 7.48052 US gal. A US gallon and an imperial gallon are different: 1 US gal is about 3.785 L, while 1 imperial gal is about 4.546 L. Label the gallon system. Convert dimensions to one consistent unit before multiplying; mixing metres, centimetres, feet, and inches is a frequent source of errors.' },
      { title: 'Theoretical volume versus usable capacity', content: 'Theoretical capacity assumes the stated geometry fills completely. Real usable capacity can be lower because of freeboard, overflow level, outlet position, unusable bottom volume, internal components, sediment allowance, and operating controls. Manufacturer-rated nominal capacity can also use its own convention. For an existing tank, use the actual operating liquid height rather than overall shell height. Do not infer a safe fill level from geometry alone.' },
      { title: 'From water demand to tank sizing', content: 'A planning approach is:\n\nRequired usable storage = expected daily demand × desired reserve days + separately required storage\n\nDemand depends on occupancy, fixtures, irrigation, supply reliability, season, conservation, and local rules. Fire reserves or process storage should be determined under applicable requirements, not guessed. After choosing usable storage, select a nominal tank whose usable volume meets it under the manufacturer’s operating levels.' },
      { title: 'How to use the Water Tank Calculator', content: 'Choose the shape and unit system, then enter verified internal dimensions. For a cylinder, distinguish diameter from radius. Review cubic metres, litres, and US gallons and note that the result is theoretical geometric capacity. The tool can also calculate a sphere, but actual manufactured tanks may not be perfect geometric shapes. Ask the supplier for a certified capacity chart where precision matters.' },
      { title: 'Measurement and safety mistakes to avoid', content: 'Do not use outside dimensions, confuse diameter with radius, mix unit systems, ignore sloped or rounded bottoms, or treat total height as fill height. Large tanks impose substantial loads: one litre of water has roughly one kilogram of mass under ordinary conditions. Tank support, foundations, anchorage, access, overflow, backflow protection, and water hygiene require appropriate design and local guidance.' },
    ], [
      { question: 'How do I calculate cistern capacity?', answer: 'Use the formula for its internal shape and operating liquid height. Irregular cisterns may need drawings, a capacity table, or subdivision into simpler volumes.' },
      { question: 'Is tank volume the same as usable water capacity?', answer: 'Not always. Freeboard, outlets, controls, sediment space, and internal fittings can reduce usable volume.' },
      { question: 'Which gallon does the calculator show?', answer: 'The Navorika tool reports US gallons. Convert separately when imperial gallons are required.' },
      { question: 'Can this calculator determine the structurally safe tank size?', answer: 'No. It calculates geometry only; support and tank design require manufacturer and qualified professional guidance.' },
    ], 'Calculate capacity from consistent internal dimensions, then distinguish theoretical volume from usable storage and verify structural and operational requirements separately.'),

  'how-to-calculate-roof-area': article('new-roof', 'How to Calculate Roof Area', 'Calculate simple pitched roof area from footprint and pitch.',
    'Roof footprint is the horizontal plan projection; roof surface area follows the slope and is larger when the roof is pitched. For a simple roof with uniform pitch, a pitch multiplier converts horizontal area to sloped area. Complex intersections, curves, unequal slopes, and dormers need a measured roof plan or professional takeoff.', [
      { title: 'Measure the horizontal roof footprint', content: 'Measure building length and width at the roof plan, including the horizontal projection of eave and gable overhangs where relevant. For a simple rectangle, footprint area = plan length × plan width. Do not measure a sloping rafter as the plan width. Divide L-shaped plans into non-overlapping rectangles, calculate each footprint, and add them.' },
      { title: 'Convert rise and run to a pitch multiplier', content: 'For rise and horizontal run in the same units:\n\nPitch multiplier = √(1 + (rise ÷ run)²)\nRoof surface area = horizontal footprint area × pitch multiplier\n\nFor a 6:12 pitch, multiplier = √(1 + 0.5²) ≈ 1.118. The Roof Pitch Calculator converts rise/run to angle, percent slope, and multiplier; it does not size rafters.' },
      { title: 'Worked gable-roof example', content: 'A simple rectangular roof plan including overhangs measures 42 ft × 30 ft. Horizontal footprint is 1,260 ft². At 6:12 pitch, sloped area is 1,260 × 1.118 ≈ 1,409 ft². If an illustrative 10% purchasing allowance is appropriate for the chosen product and layout, order-area planning becomes about 1,550 ft². Waste is not part of geometric roof area, so show it separately.' },
      { title: 'Gable and simple hip roofs', content: 'For a symmetrical gable roof with one pitch, multiplying the complete horizontal footprint works because both roof planes are represented in the projection. The same principle can work for a simple hip roof when all planes share one pitch and fully cover the footprint. Hip cuts, ridge caps, starter courses, valleys, flashing, and product packaging still affect material quantities. Mixed pitches or additions should be calculated plane by plane.' },
      { title: 'Waste and material planning', content: 'Waste depends on roof shape, valleys, hips, penetrations, product dimensions, fastening pattern, bundle coverage, and installer method. A simple rectangle may need less cutting than a complex roof with the same area. Confirm whether manufacturer coverage is net installed coverage and whether ridge, hip, underlayment, flashing, and fasteners are measured separately.' },
      { title: 'How to use the Roof Area Calculator', content: 'Enter plan length and width, uniform rise per 12 units of run, horizontal overhang, and a custom waste percentage. Keep all length inputs in the tool’s stated units. Review base footprint, pitch multiplier, roof surface, and waste-adjusted planning area separately. The calculator is intended for a simple uniformly pitched roof, not every geometry.' },
    ], [
      { question: 'Is roof area the same as house floor area?', answer: 'No. Roof overhangs and pitch usually make roof surface area larger than the building floor footprint.' },
      { question: 'Does pitch multiplier include waste?', answer: 'No. It converts horizontal projection to sloped geometric area. Waste is a separate purchasing allowance.' },
      { question: 'Can I use this for a roof with multiple pitches?', answer: 'Calculate each plane or pitch zone separately. A single multiplier would be misleading.' },
      { question: 'Does roof area determine structural capacity?', answer: 'No. Loads, framing, connections, drainage, and code compliance require separate design.' },
    ], 'Measure the horizontal projection, apply the correct multiplier to each uniform pitch, and keep geometric area separate from product-specific waste.'),

  'flooring-calculation-guide': article('new-floor', 'How to Calculate Flooring', 'Plan flooring area, packs, cuts, and waste.',
    'A useful flooring estimate separates net floor area from order quantity. Room geometry provides the net area; pack coverage, pattern, cuts, defects, matching, and future repairs determine how much material to purchase.', [
      { title: 'Calculate one room or several rooms', content: 'For a rectangle, area = length × width. Split L-shaped or irregular rooms into non-overlapping rectangles, calculate each, and add them. For multiple rooms, keep a small schedule of room name, dimensions, net area, and unit. Subtract permanent exclusions only when the installation truly will not cover them; many small deductions add measurement risk without saving a pack.' },
      { title: 'Square feet and square metres', content: 'Use consistent units before multiplying. One square metre is about 10.7639 square feet; one square foot is about 0.092903 square metres. Do not convert a length with an area factor. Either convert both length dimensions first, or calculate area and then use the square-unit conversion.' },
      { title: 'Waste, layout, and cutting', content: 'Straight layouts in regular rooms often create fewer offcuts than diagonal, herringbone, bordered, or heavily staggered layouts. Alcoves, columns, doorways, damaged pieces, colour or grain matching, and installer experience also matter. Choose a waste allowance for the actual product and plan rather than treating one percentage as universal. Keep waste-adjusted order area visible separately from measured area.' },
      { title: 'Convert area into packs', content: 'Packs needed = ceiling(order area ÷ verified pack coverage). Suppose two rooms total 418 ft² and a chosen 8% allowance produces 451.44 ft². If each pack states 22.5 ft² of installed coverage, 451.44 ÷ 22.5 = 20.064, so round up to 21 packs. Check batch or dye-lot availability and decide whether a spare sealed pack is appropriate for later repair.' },
      { title: 'Planks, tiles, and coverage claims', content: 'Individual plank or tile count can be estimated from piece coverage, but packaged coverage is usually the better purchasing input. Joint width, fixed orientation, pattern repeats, breakage, and edge cuts change piece counts. Use the Tile Calculator when grid count and joint gap are central; use the Flooring Calculator for area, rates, and broad waste-adjusted cost planning.' },
      { title: 'How to use the Flooring Calculator', content: 'Enter room length and width, select or enter the relevant flooring assumptions, then enter your actual material and installation rates and a chosen waste allowance. The tool handles one rectangle at a time, so aggregate carefully for several rooms or run each room separately. Verify pack coverage and current quotations before ordering.' },
    ], [
      { question: 'Should I subtract kitchen cabinets?', answer: 'Only if the flooring will not run beneath them and the installation plan is settled. Confirm with the installer and product requirements.' },
      { question: 'How much flooring waste should I add?', answer: 'There is no universal percentage. Room shape, pattern, product, defects, batch matching, and installer method determine it.' },
      { question: 'Why must packs be rounded up?', answer: 'Suppliers generally sell complete packs, so a fractional result must be rounded to the next whole pack.' },
      { question: 'Can the calculator plan a herringbone layout?', answer: 'It can apply a user-entered area allowance, but it does not model the detailed pattern or every cut.' },
    ], 'Measure each room consistently, total the net area, apply a layout-specific allowance, and round by verified pack coverage.'),

  'asphalt-calculation-guide': article('new-asphalt', 'How to Calculate Asphalt Volume & Tonnage', 'Estimate asphalt quantities without treating density as universal.',
    'Asphalt planning moves through four steps: area, compacted thickness, volume, and mass. The arithmetic is straightforward, but density, compaction, lift design, subgrade, and plant ordering requirements are project-specific.', [
      { title: 'Area and compacted depth', content: 'For a rectangular driveway, area = length × width. Divide irregular paving into measured shapes and avoid overlap. Convert the specified compacted thickness to the same base unit before multiplying. A common error is entering millimetres as metres: 50 mm is 0.05 m, not 50 m.' },
      { title: 'Volume and tonnage formulas', content: 'Volume = area × compacted thickness\nMass = volume × compacted density\nMetric tonnes = kilograms ÷ 1,000\n\nFor imperial measurements, calculate cubic feet, convert as needed, and use a compatible density unit. Density must describe the relevant compacted mix and conditions; aggregate type, binder, temperature, and achieved compaction all affect it.' },
      { title: 'Worked driveway example', content: 'A 20 m × 4 m driveway has 80 m² of area. At 50 mm compacted thickness, volume is 80 × 0.05 = 4.0 m³. Using an illustrative project assumption of 2,350 kg/m³ gives 9,400 kg, or 9.4 metric tonnes before allowance. If a chosen 5% planning allowance is justified, the order estimate is 9.87 tonnes. The density and allowance are examples, not universal values.' },
      { title: 'Waste, compaction, and delivery planning', content: 'Do not casually add a “compaction factor” when the density and depth already refer to compacted material; that can double-count. Allowance may cover small placement losses, geometry, minimum plant quantities, or uncertainty, but should be documented. Contractors may plan several lifts, joints, tack coat, transport, paving sequence, truck payload, and temperature windows separately.' },
      { title: 'How to use the Asphalt Calculator', content: 'Enter length, width, compacted design thickness, a density supplied for the mix, and a chosen waste percentage. Review cubic volume and tonnes. The displayed truck count is only an illustration based on the tool’s stated payload assumption; actual legal payload and supplier dispatch rules vary. Confirm quantities with the asphalt plant and paving contractor.' },
      { title: 'What quantity alone cannot tell you', content: 'A tonnage result does not establish pavement thickness, drainage, subgrade preparation, base course, mix selection, compaction target, or structural suitability. Those decisions depend on traffic, soil, climate, standards, and site conditions.' },
    ], [
      { question: 'What asphalt density should I use?', answer: 'Use a value supplied for the selected mix and relevant compacted condition. No single density is exact for all asphalt.' },
      { question: 'Should thickness be loose or compacted?', answer: 'Use the thickness and density on the same basis. The Navorika tool asks for compacted design thickness and compacted density.' },
      { question: 'Does tonnage include base material?', answer: 'No. Asphalt and aggregate base are separate materials and should be estimated separately.' },
      { question: 'Can this design a driveway pavement?', answer: 'No. It estimates quantity from user inputs; pavement design needs site-specific expertise.' },
    ], 'Use consistent units and a project-specific compacted density, then confirm mix, layers, allowances, and delivery quantities with the supplier and contractor.'),

  'gravel-calculation-guide': article('new-gravel', 'How to Calculate Gravel', 'Estimate gravel volume and weight for driveways and landscaping.',
    'Gravel is bought by volume or weight, so a good estimate calculates both and states the material condition. Particle size, moisture, grading, angularity, and compaction change bulk density and finished depth.', [
      { title: 'Area multiplied by depth', content: 'For a rectangular layer:\n\nVolume = length × width × depth\n\nConvert depth before multiplying. For example, 3 inches is 0.25 ft. A 40 ft × 10 ft driveway at 3 inches has 40 × 10 × 0.25 = 100 ft³ of geometric volume. Divide by 27 to get about 3.70 yd³ before any allowance.' },
      { title: 'Convert volume to tonnes', content: 'Weight = volume × bulk density. Use supplier density for the named gravel in its expected loose or compacted and moisture condition. “Gravel” can mean pea gravel, river rock, crushed stone, or a graded road-base blend, and their bulk densities differ. A calculator preset is a planning assumption, not a material certificate.' },
      { title: 'Loose delivery versus compacted finished layer', content: 'A finished compacted volume may require more loose delivered volume because particles rearrange under compaction. The relationship depends on gradation, moisture, equipment, and target density. Ask the supplier or contractor for a conversion appropriate to the product. Do not automatically apply both a loose-to-compacted factor and a density assumption that already represents the conversion.' },
      { title: 'Allowances and worked planning', content: 'If supplier guidance converts the 3.70 yd³ geometric need to 4.15 yd³ loose delivery and the site plan justifies a further small allowance for uneven grade, document each step rather than hiding both in one percentage. Round according to bag size, bulk increment, or truck policy. Verify access and axle/load limits before arranging a bulk delivery.' },
      { title: 'Driveways and landscaping', content: 'Driveway quantity depends on excavated grade, edge restraint, base and surface layers, drainage, and compaction. Landscaping beds may use decorative gravel at a different depth and often need geotextile or edging decisions. Separate soil excavation from imported gravel. The Sand, Topsoil, Mulch, and Paver calculators support adjacent landscape quantities.' },
      { title: 'How to use the Gravel Calculator', content: 'Enter the measured rectangular dimensions and depth, then select the closest supported gravel type. Review cubic metres, tonnes, and the tool’s indicative load count. Because its density presets and truck capacity are generic, replace them with a supplier quotation when ordering.' },
    ], [
      { question: 'How many cubic feet are in a cubic yard?', answer: 'There are 27 cubic feet in one cubic yard.' },
      { question: 'Why do gravel tonnes vary for the same volume?', answer: 'Material type, grading, voids, moisture, and compaction change bulk density.' },
      { question: 'Should I calculate loose or compacted gravel?', answer: 'Start from required finished geometry, then use product-specific supplier guidance to convert to delivered quantity.' },
      { question: 'Does the calculator include settlement?', answer: 'Its built-in result uses stated geometric and density assumptions; site-specific compaction or settlement must be handled separately.' },
    ], 'Calculate finished volume first, use material-specific density and loose/compacted guidance, and round to the supplier’s actual sales unit.'),

  'electricity-cost-calculation-guide': article('new-electricity', 'How to Calculate Electricity Cost', 'Calculate appliance energy and running cost from watts and kWh.',
    'Electricity cost depends on energy, not power alone. Watts describe the rate at which an appliance uses energy; kilowatt-hours combine that power with operating time. Multiply energy by the tariff that actually applies to estimate usage cost.', [
      { title: 'Watts, kilowatts, and kWh', content: 'Convert watts to kilowatts by dividing by 1,000. Then:\n\nEnergy (kWh) = power (kW) × hours\nCost = energy (kWh) × electricity rate per kWh\n\nA 100 W device running for 5 hours uses 0.1 kW × 5 h = 0.5 kWh. Watt is a power unit; kWh is an energy unit, despite the common phrase “kilowatts per hour.”' },
      { title: 'Daily, monthly, and annual examples', content: 'Suppose a 1,500 W heater runs 2 hours per day. Daily energy is 1.5 × 2 = 3 kWh. At an illustrative user-entered rate of 0.20 currency units per kWh, daily usage cost is 0.60, a 30-day estimate is 18.00, and a 365-day estimate is 219.00. The tariff is only an example; enter the current rate from your bill.' },
      { title: 'Duty cycles and variable power', content: 'Rated watts may be maximum input rather than average use. Refrigerators, air conditioners, pumps, and thermostatically controlled heaters cycle on and off. Computers and variable-speed equipment change load. For better estimates, use a measured average from a suitable energy meter or multiply rated power by a defensible duty-cycle assumption.' },
      { title: 'Standby use and multiple appliances', content: 'A small continuous standby load can accumulate. A 5 W load operating 24 hours uses 0.12 kWh per day. For several appliances, calculate each device using its own watts and runtime, then add kWh and cost. This is clearer than adding wattages when their schedules differ.' },
      { title: 'Tariffs and the full bill', content: 'A simple energy-rate estimate may not match the final bill. Real tariffs can include fixed charges, taxes, slabs or tiers, time-of-use prices, demand charges, fuel adjustments, minimum charges, export credits, or subsidies. Derive an appropriate marginal or average rate from the bill according to the decision being made, and do not hard-code a universal tariff.' },
      { title: 'How to use the Electricity Cost Calculator', content: 'Enter appliance wattage, average hours per day, number of days, and your current rate per kWh. Review energy and daily, 30-day, annual, and selected-period cost. Repeat for each appliance when building a household estimate. The tool estimates usage charges and does not reproduce every utility billing rule.' },
    ], [
      { question: 'How do I convert watts to kWh?', answer: 'Divide watts by 1,000, then multiply by hours of operation.' },
      { question: 'Can I use the wattage on the label?', answer: 'Yes for a rough upper-bound or steady-load estimate, but cycling and variable-power devices may use less on average.' },
      { question: 'Why does the result differ from my bill?', answer: 'Bills may include other loads, fixed fees, taxes, tiered prices, demand charges, and changing usage.' },
      { question: 'How do I include standby power?', answer: 'Calculate the standby wattage over its actual hours—often close to 24 per day—and add that energy separately.' },
    ], 'Convert power to kW, multiply by realistic runtime, and apply the current relevant tariff while keeping broader bill charges separate.'),

  'brick-calculation-guide': article('new-brick', 'How to Calculate Bricks for a Wall', 'Estimate brick count with openings, mortar joints, and waste.',
    'Brick quantities depend on wall geometry and the actual masonry unit, joint, bond, and wall thickness. Brick sizes vary by country, standard, manufacturer, and product, so measure or verify the specified unit rather than relying on a universal bricks-per-area rule.', [
      { title: 'Measure net wall area', content: 'Gross wall area = wall length × wall height. Subtract measured doors, windows, and other openings to obtain net face area when using an area method. Keep units consistent. For several walls, calculate each separately so thickness and opening assumptions remain traceable.' },
      { title: 'Brick size plus mortar joint', content: 'A nominal module combines the actual brick face dimensions with the specified mortar joint. For a simple face-area estimate:\n\nBricks per area ≈ 1 ÷ ((brick length + joint) × (brick height + joint))\n\nThis assumes the stated orientation and regular joints. Bond pattern, closures, piers, returns, and wall ends affect the count.' },
      { title: 'Wall-volume method and thickness', content: 'The Navorika calculator uses wall volume divided by a nominal brick-and-joint module, so wall thickness is explicit. This is useful for comparing thicker masonry, but real bond geometry and mortar distribution are more complicated than a repeating box. Confirm whether dimensions are actual or nominal and whether the tool’s orientation matches the work.' },
      { title: 'Worked metric example', content: 'A 6 m × 2.7 m wall has 16.2 m² gross area. A 1.2 m × 1.5 m opening removes 1.8 m², leaving 14.4 m². If the specified brick-and-joint face module were illustratively 0.21 m × 0.075 m, one-layer face count is 14.4 ÷ 0.01575 ≈ 915 bricks before bond details and allowance. Do not reuse this module for a different brick or joint.' },
      { title: 'Waste, breakage, and ordering', content: 'Cuts, breakage, colour blending, complex bonds, site handling, and supplier pack quantities influence the purchasing allowance. Salvage and return policies also matter. Keep base geometric count and allowance visible separately, round up to complete packs or pallets, and confirm matching batches for exposed work.' },
      { title: 'How to use the Brick Calculator', content: 'Enter wall length, height, and thickness; actual brick dimensions; mortar-joint thickness; and a project-specific waste percentage. Adjust for openings before entry if the current interface does not provide separate opening fields. Review brick count and mortar-related outputs as planning estimates, then check drawings, bond, specification, and supplier units.' },
    ], [
      { question: 'How many bricks are in a square metre?', answer: 'There is no universal number. It depends on brick face size, orientation, mortar joint, and bond.' },
      { question: 'Should openings be subtracted?', answer: 'Usually yes when they are large and confirmed, while small openings and detailing may be handled according to the estimator’s measurement rules.' },
      { question: 'Are nominal and actual brick sizes the same?', answer: 'Not necessarily. Nominal dimensions may include the intended mortar module; verify the manufacturer specification.' },
      { question: 'Does the calculator design the wall?', answer: 'No. Structural, fire, moisture, movement-joint, and code requirements need appropriate design.' },
    ], 'Use verified brick and joint dimensions, calculate net wall geometry, and adjust for the actual bond, thickness, cuts, and supplier packaging.'),

  'dimensional-weight-guide': article('new-dim', 'Dimensional Weight Guide', 'Understand dimensional, actual, and billable shipping weight.',
    'Dimensional weight—also called volumetric weight—converts the space a package occupies into a comparison weight. Carriers use it because a large light carton can consume vehicle or aircraft capacity long before the payload limit is reached.', [
      { title: 'Actual, dimensional, and billable weight', content: 'Actual weight is measured on a scale. Dimensional weight is calculated from package volume and a divisor. Billable weight is commonly based on the greater of actual and dimensional weight, after the carrier applies its own measurement, rounding, minimum, oversize, service, and packaging rules.' },
      { title: 'Metric and imperial formulas', content: 'A general formula is:\n\nDimensional weight = length × width × height ÷ divisor\n\nUse dimensions and a divisor designed for the same unit system. A divisor expressed for centimetres and kilograms cannot be used unchanged with inches and pounds. Measure the package’s outermost dimensions, including bulges or projections, as the carrier instructs.' },
      { title: 'Worked example with an illustrative divisor', content: 'Consider a 50 cm × 40 cm × 30 cm carton. Volume is 60,000 cm³. Using an illustrative divisor of 5,000 cm³/kg gives dimensional weight of 12 kg. If scale weight is 7 kg, the comparison points to 12 kg before carrier rounding. The divisor is an example only; obtain the current divisor for the carrier, service, route, and account.' },
      { title: 'Why divisors differ', content: 'A smaller divisor produces a larger dimensional weight. Carriers can publish different divisors for domestic and international services, air and ground products, retail and contracted accounts, or particular packaging. Rules can change. Some carriers round each dimension before calculation and then round weight upward, which can make a quote differ from unrounded arithmetic.' },
      { title: 'Reduce avoidable package volume', content: 'Choose a carton close to the protected item size, remove unnecessary void, and use packaging that still meets damage-prevention requirements. Reducing volume is not worthwhile if it increases breakage, violates dangerous-goods rules, or loses required cushioning. Compare packaging and shipping cost together.' },
      { title: 'How to use the Dimensional Weight Calculator', content: 'Choose metric or imperial, enter external length, width, height, actual weight, and the divisor published for the shipment. Compare actual, dimensional, and estimated billable weight. Treat the result as a pre-shipment estimate and verify the carrier’s current rounding, oversize, and rate rules.' },
    ], [
      { question: 'Is volumetric weight the same as dimensional weight?', answer: 'They are commonly used for the same space-based shipping concept.' },
      { question: 'Which divisor should I use?', answer: 'Use the current divisor published or contracted for the exact carrier, service, route, unit system, and account.' },
      { question: 'Why did the carrier measure a higher weight?', answer: 'Its measured dimensions, dimension rounding, weight rounding, oversize rules, or divisor may differ from your assumptions.' },
      { question: 'Is dimensional weight a shipping price?', answer: 'No. It is a billing-weight input; zones, services, surcharges, and account rates still determine price.' },
    ], 'Measure the packed outer carton, use the exact service-specific divisor, and compare dimensional with scale weight under the carrier’s current rounding rules.'),

  'construction-estimate-quote-guide': article('new-estimate', 'Construction Estimate & Quote Guide', 'Build clear, traceable construction estimates and quotes.',
    'A client-ready construction estimate should make scope, quantities, rates, assumptions, and commercial adjustments understandable. A polished total without a defined scope is not a reliable estimate. Terminology also varies: “estimate,” “quote,” “proposal,” and “bid” can carry different meanings by jurisdiction and business practice.', [
      { title: 'Estimate versus quote', content: 'An estimate generally communicates an anticipated cost based on stated information and uncertainty. A quote may communicate a firmer offered price for a defined scope and validity period, but the legal effect depends on wording, local law, acceptance, and the surrounding contract process. Label documents consistently with professional and legal advice; a generator cannot determine whether a document is contractually binding.' },
      { title: 'Define project scope before pricing', content: 'Record client and site, drawing and revision references, inclusions, exclusions, allowances, schedule assumptions, measurement basis, procurement method, and who supplies permits or utilities. Break the scope into work packages or a work breakdown structure. Scope gaps create more risk than a perfectly calculated markup can fix.' },
      { title: 'Build quantities and direct costs', content: 'For each line item, record description, quantity, unit, and unit rate. Line cost = quantity × rate. Separate materials, labour, equipment, subcontractors, and other direct costs when useful. Rates should come from current supplier quotations, wage and productivity assumptions, subcontractor proposals, and project conditions—not unsupported generic prices.' },
      { title: 'Overhead, markup, contingency, and tax', content: 'Overhead covers business or project costs not assigned directly to one item. Markup is an addition used to reach the selling price; margin is profit divided by selling price, so markup percentage and margin percentage are not interchangeable. Contingency should correspond to identified uncertainty and must not hide omitted scope. Tax treatment depends on jurisdiction and transaction facts. State each calculation base to prevent double-counting.' },
      { title: 'A practical example structure', content: 'A concise document can include: header and estimate number; client/project details; scope summary; itemized quantities and rates; direct-cost subtotal; overhead; contingency or allowances; markup; discount if any; tax if applicable; total; assumptions and exclusions; schedule or payment notes; quote validity; and acceptance or next-step instructions. Version and date the document so changes are traceable.' },
      { title: 'Client-ready workflow with Navorika tools', content: 'Use trade calculators such as Brick, Flooring, Roof Area, Gravel, or House Construction Cost to develop planning quantities, then transfer verified quantities and current rates into the Construction Estimate Builder. The Contractor Estimate Generator supports contractor-branded commercial presentation. The Construction Cost Calculator provides a broader early cost split. Review every exported line, tax entry, assumption, and exclusion before sharing.' },
      { title: 'Quality-control checklist', content: 'Check arithmetic, units, scope coverage, duplicate items, drawing revisions, supplier quotation dates, labour productivity, equipment duration, subcontractor exclusions, escalation, contingency basis, overhead and markup bases, tax, rounding, quote validity, and document version. Have the responsible estimator review the output; software formatting does not validate the underlying scope.' },
    ], [
      { question: 'Is an estimate the same as a quote?', answer: 'Not necessarily. Usage and legal effect vary by business practice, wording, jurisdiction, and contract process.' },
      { question: 'Should markup be added to labour and material?', answer: 'That depends on the company’s pricing method. State the calculation base and avoid counting overhead or profit twice.' },
      { question: 'What should exclusions contain?', answer: 'Clearly list work, fees, conditions, or risks not included so the client can compare offers and request clarifications.' },
      { question: 'Does the estimate builder supply market rates?', answer: 'No. Users must enter current project-specific quantities, rates, tax assumptions, and commercial terms.' },
    ], 'A strong estimate is traceable from scope to quantities to rates, with commercial additions and exclusions stated clearly and reviewed by the responsible professional.'),

  'base64-encoding-guide': article('base64', 'Base64 Encoding Guide', 'Understand Base64, Base64url, padding, Unicode, and security.',
    'Base64 represents bytes using printable ASCII characters. It helps binary data travel through text-oriented systems, but it does not encrypt, authenticate, compress, or protect that data. Anyone who has the encoded value can usually decode it.', [
      { title: 'How Base64 encoding works', content: 'Base64 reads input bytes in groups of three: 24 bits. It divides those bits into four 6-bit values and maps each value to one of 64 alphabet characters. The standard alphabet uses A–Z, a–z, 0–9, plus, and slash. Because four text characters represent three source bytes, Base64 typically adds about 33% size overhead before line breaks, data-URL prefixes, or other wrapping.' },
      { title: 'Padding and the equals sign', content: 'When the byte count is not divisible by three, the final group is incomplete. Standard Base64 commonly uses one or two equals signs as padding so the encoded length aligns to a four-character group. Padding is metadata about the final group, not encrypted content. Some specifications permit or require omitted padding, so decoding should follow the relevant protocol.' },
      { title: 'Base64url and JWT segments', content: 'Base64url replaces plus with hyphen and slash with underscore, making the alphabet safer in URLs and filenames; padding is often omitted. It is a related encoding, not simply arbitrary standard Base64 text. JWT header and payload segments use Base64url, while their decoded bytes normally contain JSON.' },
      { title: 'Text, Unicode, and decoding', content: 'Base64 operates on bytes, not abstract characters. Text must first be encoded as bytes—usually UTF-8—and decoded bytes must be interpreted with the same character encoding. Applying browser btoa directly to arbitrary Unicode text can fail or corrupt characters unless UTF-8 conversion is handled. A successful Base64 decode can also produce bytes that are not valid text.' },
      { title: 'Common uses', content: 'Base64 appears in MIME email transfer, data URLs, small embedded images, API payloads, certificates, and tokens. It can simplify transport through text-only channels but increases size and may reduce cacheability or readability. For large binary files, a normal binary upload or file URL is often more efficient.' },
      { title: 'Common errors and security misconceptions', content: 'Errors include confusing Base64 with Base64url, missing or invalid padding, whitespace inserted by transport, invalid alphabet characters, decoding bytes with the wrong character set, or assuming every decoded result is readable text. Encoding secrets does not secure them. Sensitive values still require appropriate access control and encryption; decoded JWT claims remain untrusted until signature and claim validation succeeds.' },
      { title: 'Using the Base64 Encoder', content: 'Enter text to encode it as UTF-8 Base64, or paste Base64 to decode bytes as strict UTF-8. Work locally when values are sensitive and inspect errors instead of silently accepting replacement characters. Use the JWT Decoder for token segments and JSON Formatter for decoded structured data.' },
    ], [
      { question: 'Is Base64 encryption?', answer: 'No. It is reversible encoding and provides no confidentiality.' },
      { question: 'Why is Base64 larger than the original?', answer: 'Four Base64 symbols represent each three-byte group, creating roughly one-third overhead before wrappers.' },
      { question: 'What does equals padding mean?', answer: 'It marks an incomplete final three-byte group so standard output aligns to four characters.' },
      { question: 'Can Base64 encode images?', answer: 'Yes, it can represent image bytes, often in a data URL, but size and caching tradeoffs should be considered.' },
      { question: 'Are Base64 and Base64url interchangeable?', answer: 'Not always. Their alphabets and padding conventions differ, so use the variant required by the protocol.' },
    ], 'Base64 is a byte-to-text transport encoding: choose the correct variant and character encoding, expect size overhead, and never treat it as security.'),

  'jwt-decoding-guide': article('jwt', 'JWT Decoding Guide', 'Decode JWT structure without confusing inspection with verification.',
    'A compact JSON Web Token commonly has three period-separated segments: header.payload.signature. Decoding the first two segments makes their JSON readable. It does not prove who created the token, whether it was altered, whether its claims apply to your application, or whether it is currently acceptable.', [
      { title: 'Header, payload, and signature', content: 'The header describes token-processing information such as alg and often typ. The payload contains claims. The signature is computed from protected input using the declared and permitted algorithm plus a key. Each compact segment uses Base64url. A malformed token may have the wrong segment count, invalid Base64url, non-UTF-8 bytes, or invalid JSON.' },
      { title: 'Registered claims to recognize', content: 'Common names include iss (issuer), sub (subject), aud (audience), exp (expiration time), nbf (not before), and iat (issued at). In the header, alg identifies an algorithm and typ can identify the token type. A decoder should display these values as untrusted data. Applications must define expected issuer, audience, algorithms, keys, time tolerance, and required claims.' },
      { title: 'Decoding is not signature verification', content: 'Anyone can create three Base64url segments or change a payload. Verification cryptographically checks the signature with a trusted key and an explicitly allowed algorithm. Secure validation also checks claims and application context. Never accept an algorithm merely because the untrusted header requests it, and never describe a token as valid because it decodes cleanly.' },
      { title: 'Expiration and time claims', content: 'exp is generally a NumericDate after which the token must not be accepted; nbf indicates a time before which it must not be accepted; iat records issuance time. Displaying a human-readable timestamp is convenient, but acceptance requires correct clock handling, reasonable skew policy, and other validation. An unexpired token can still have an invalid signature or wrong audience.' },
      { title: 'Privacy and safe debugging', content: 'JWT payloads are encoded, not encrypted, unless a separate encrypted token format is used. They can expose names, identifiers, scopes, or internal metadata to anyone holding the token. Do not paste production access or refresh tokens into unknown sites, tickets, chat, logs, or screenshots. Redact tokens and prefer local inspection.' },
      { title: 'Using the JWT Decoder', content: 'Paste a compact token to inspect locally decoded UTF-8 JSON from its header and payload. Use the JSON Formatter for nested claims and the Base64 guide to understand Base64url. The tool intentionally does not verify the signature or trust claims, so use your application’s maintained JWT library and trusted configuration for verification.' },
    ], [
      { question: 'Does decoding a JWT validate it?', answer: 'No. Validation requires signature verification and application-specific claim checks.' },
      { question: 'Can I edit a decoded JWT?', answer: 'You can change text, but that invalidates the original signature. A verifier should reject the altered token.' },
      { question: 'Does exp prove a token is safe to accept?', answer: 'No. It is only one untrusted claim until the signature, issuer, audience, algorithm, time, and other requirements are validated.' },
      { question: 'Why will a JWT not decode?', answer: 'It may have the wrong number of segments, invalid Base64url, invalid UTF-8 or JSON, or it may not be a compact JWT.' },
      { question: 'Are JWT payloads private?', answer: 'Normally no. Signed JWT payloads are readable; avoid putting unnecessary secrets or sensitive personal data in them.' },
    ], 'Use decoding for inspection only. Trust a JWT only after cryptographic verification and complete application-specific claim validation.'),

  'json-formatting-guide': article('json', 'JSON Formatting Guide', 'Work safely with JSON formatting, validation, conversion, and comparison.',
    'JSON is a strict text format for exchanging structured data. Pretty printing changes whitespace for readability; minification removes unnecessary whitespace. Both operations depend on parsing, while schema validation, flattening, conversion, and comparison answer different questions.', [
      { title: 'Valid JSON values and structure', content: 'JSON values can be objects, arrays, strings, numbers, booleans, or null. Objects contain comma-separated name/value members inside braces; arrays contain comma-separated values inside brackets. Property names and strings require double quotes. Standard JSON has no comments, trailing commas, undefined, functions, NaN, or Infinity.' },
      { title: 'Quoting, commas, numbers, and escaping', content: 'Use a colon between an object key and value and commas only between members or elements. Escape a quote inside a string as \\" and a backslash as \\\\. Control characters require valid escapes. JSON number grammar rejects leading plus signs, hexadecimal notation, and some language-specific numeric forms. Parser errors often point just after the real mistake, so inspect the preceding quote, comma, or bracket.' },
      { title: 'Pretty printing, minification, and validation', content: 'A formatter parses and serializes with indentation; a minifier serializes without presentation whitespace. Syntax validation asks whether the text follows JSON grammar. Schema validation asks whether valid JSON has required properties, types, formats, and constraints. Formatting cannot repair ambiguous invalid input safely, and valid syntax does not guarantee the data is correct for an API.' },
      { title: 'JSON versus JavaScript object literals', content: 'JavaScript object literals can allow unquoted identifier keys, single-quoted strings, comments, trailing commas, methods, undefined, and computed values. Those features do not make valid JSON. JSON.parse accepts JSON text; evaluating unknown text as JavaScript is unsafe and unnecessary.' },
      { title: 'Flattening and JSON/CSV conversion', content: 'Flattening turns nested paths into columns or key paths, but arrays, repeated records, missing values, and nested objects require explicit conventions. JSON to CSV works best with a consistent array of records; CSV to JSON requires choices about headers, empty cells, delimiters, and type inference. Preserve an original source and review round trips because CSV cannot represent every JSON structure without loss or conventions.' },
      { title: 'Schema validation and diff/compare', content: 'Use JSON Schema Validator when a payload must meet a contract, and JSON Diff & Compare to find structural or value changes between two documents. A textual diff can be noisy when only formatting or key order changes; a parsed structural comparison is often more useful. JWT payloads can be formatted as JSON after decoding but remain untrusted until token verification.' },
      { title: 'Privacy and practical tool workflow', content: 'Production payloads may contain credentials, tokens, personal data, or confidential configuration. Redact them and prefer local tools. Start with JSON Formatter for syntax, then use schema validation, diff, JSON to CSV Flattener, or CSV to JSON Converter according to the task. Large documents can exceed browser memory because both source text and parsed objects may be retained.' },
    ], [
      { question: 'Does JSON allow single quotes?', answer: 'No. JSON strings and object property names use double quotes.' },
      { question: 'Is pretty JSON more valid than minified JSON?', answer: 'No. Whitespace outside strings does not determine validity.' },
      { question: 'Can a formatter fix invalid JSON?', answer: 'It can report a parse error, but automatic repair may guess incorrectly. Correct the source based on intended data.' },
      { question: 'What is the difference between JSON validation and schema validation?', answer: 'Syntax validation checks JSON grammar; schema validation checks the permitted structure and values of already valid JSON.' },
      { question: 'Is JSON to CSV always reversible?', answer: 'No. Nested structures, arrays, types, and missing values may be flattened or represented with conventions that lose information.' },
    ], 'Treat formatting, syntax validation, schema checking, conversion, and comparison as distinct steps, and keep sensitive data in a trusted local workflow.'),

  'heart-rate-zones-guide': article('heart', 'Heart Rate Zones Guide', 'Understand target zones and their limitations.',
    'Heart-rate zones divide exercise intensity into ranges, usually from an estimated maximum heart rate or heart-rate reserve. They can support training conversations, but an age formula is a population estimate—not a diagnosis, medical clearance, or personalized ceiling.', [
      { title: 'Resting, maximum, and target heart rate', content: 'Resting heart rate is commonly measured when awake, calm, and seated or lying down. Maximum heart rate is the highest rate reached during maximal effort; age equations only estimate it. A target zone is a chosen percentage range used as an intensity guide. Heart rate responds to fitness, heat, hydration, stress, illness, altitude, caffeine, medication, and many other factors.' },
      { title: 'Percentage of estimated maximum', content: 'The Navorika tool uses the simple estimate 220 − age. A target is then estimated maximum × chosen percentage. The American Heart Association describes broad guides of about 50–70% of maximum for moderate activity and 70–85% for vigorous activity. Beginners may aim toward the lower part and progress gradually, subject to health guidance.' },
      { title: 'Heart-rate reserve method', content: 'Heart-rate reserve (HRR) = estimated maximum − resting heart rate. A reserve-based target is resting rate + intensity percentage × HRR. This incorporates the entered resting value, but it still inherits error from the maximum estimate and is not automatically individualized medical advice. Measure resting pulse consistently over several calm mornings when using it for training context.' },
      { title: 'Worked educational example', content: 'For age 40, 220 − age estimates 180 BPM. A 50–70% range is 90–126 BPM. If resting rate is 60 BPM, HRR is 120; an illustrative 60% HRR target is 60 + 0.60 × 120 = 132 BPM. These two methods answer slightly different questions and should not be presented as precise personal limits.' },
      { title: 'Wearables and perceived effort', content: 'Optical wrist sensors can vary with fit, motion, temperature, skin contact, tattoos, and rapid intensity changes. A chest strap may respond more reliably for some interval work but is still a measurement device, not medical interpretation. Cross-check with breathing, talk test, perceived exertion, pace, power, and how you feel.' },
      { title: 'How to use the Heart Rate Calculator safely', content: 'Enter a manual pulse count to convert it to BPM. Optionally enter adult age and resting heart rate to view broad maximum, percentage, and reserve-based estimates supported by the tool. Stop exercise and seek urgent medical help for chest pain, fainting, severe or unusual breathlessness, or other concerning symptoms. People with heart conditions or medicines that affect pulse should request individualized exercise guidance.' },
    ], [
      { question: 'Is 220 minus age accurate?', answer: 'It is a rough population estimate with substantial individual variation.' },
      { question: 'Which heart-rate zone method is best?', answer: 'No formula is best for everyone. HRR adds resting rate context, while supervised testing and professional guidance can provide stronger individual information.' },
      { question: 'Why does my wearable jump or lag?', answer: 'Motion, fit, cold, poor contact, and fast intensity changes can affect optical readings.' },
      { question: 'Do medicines change heart-rate zones?', answer: 'Some medicines can alter resting rate and exercise response. Ask a clinician for an appropriate intensity method.' },
      { question: 'Are target zones medical advice?', answer: 'No. They are educational training estimates and do not diagnose or clear someone for exercise.' },
    ], 'Use calculated zones as broad ranges, compare them with perceived effort, and obtain individualized guidance when symptoms, conditions, or medications are relevant.'),

  'how-to-calculate-emi': article('emi', 'EMI Calculation Guide', 'Calculate EMI for home, car, and personal loans.',
    'An equated monthly instalment (EMI) is the scheduled level payment for an amortizing loan. EMI arithmetic helps compare home, car, and personal loan scenarios, but affordability also depends on fees, insurance, changing rates, income stability, other debts, and loan terms.', [
      { title: 'Principal, rate, tenure, and the EMI formula', content: 'For a reducing-balance loan:\n\nEMI = P × r × (1 + r)^n ÷ ((1 + r)^n − 1)\n\nP is principal, r is the monthly periodic interest rate, and n is the number of monthly instalments. Convert a nominal annual percentage rate to monthly form as stated by the loan terms; a simple calculator commonly uses annual rate ÷ 12 ÷ 100. Tenure in years must be multiplied by 12.' },
      { title: 'Worked example', content: 'For an illustrative principal of 500,000 currency units, 10% annual reducing-balance rate, and 5-year tenure, r = 0.10 ÷ 12 and n = 60. The formula gives an EMI of about 10,624. Total scheduled payments are about 637,411 and total interest about 137,411, subject to rounding and payment timing. This is an arithmetic example, not a loan offer.' },
      { title: 'Reducing balance and amortization', content: 'Interest for each period is calculated on the outstanding balance. Early payments usually contain more interest because principal is highest; later payments contain more principal. An amortization schedule shows opening balance, interest, principal repaid, and closing balance. Multiplying the first month’s interest by the whole tenure is incorrect.' },
      { title: 'Personal, car, and home loan context', content: 'The same core formula can model many fixed-rate amortizing loans. Personal loans may have different fees and pricing from secured loans. Car loans may include deposits, trade-ins, balloon payments, insurance, or add-ons. Home loans may have long tenures, floating rates, staged disbursements, and significant fees. Model the amount actually financed and verify whether the product follows the assumed reducing-balance structure.' },
      { title: 'How rate and tenure change cost', content: 'A higher rate raises EMI and total interest. A longer tenure generally lowers EMI but increases total interest because the balance remains outstanding longer. Compare several terms using monthly payment, total repayment, total interest, effective cost, fees, and flexibility—not EMI alone. A low EMI can simply be a more expensive long loan.' },
      { title: 'Prepayment and rate changes', content: 'A principal prepayment can reduce future interest, but the lender may reduce EMI, shorten tenure, charge a fee, or apply product-specific rules. Floating-rate changes can alter payment or tenure. Request a revised amortization schedule and confirm how payments are allocated before relying on a projected saving.' },
      { title: 'How to use the Loan EMI Calculator', content: 'Enter principal, annual interest rate, and tenure. Review EMI, total interest, and total repayment, then test shorter tenure, higher-rate stress, and smaller principal scenarios. Use the Loan Amortization Suite for payment-by-payment detail. Add processing fees, insurance, taxes, and other costs separately if the tool does not include them.' },
    ], [
      { question: 'Is personal loan EMI calculated differently?', answer: 'The same formula often applies to fixed-rate reducing-balance loans, but fees, rate conventions, and product terms can differ.' },
      { question: 'Does a lower EMI mean a cheaper loan?', answer: 'No. Extending tenure can lower EMI while raising total interest.' },
      { question: 'What is reducing-balance interest?', answer: 'Interest is calculated on the outstanding principal, which generally declines as payments are made.' },
      { question: 'Does the calculator include processing fees?', answer: 'No unless explicitly shown. Compare fees, insurance, taxes, penalties, and effective annual cost separately.' },
      { question: 'Will prepayment always reduce EMI?', answer: 'Not necessarily. A lender may shorten tenure instead, and charges or conditions can apply.' },
    ], 'Use the existing EMI guide as the primary informational page for personal, car, and home loan intent; compare total borrowing cost and terms, not monthly payment alone.'),
};
