export const guideRelations: Record<string, string[]> = {
  'video-editing-software-for-mac': ['free-video-editing-software-for-mac', 'professional-video-editing-software-for-mac', 'easy-video-editing-software-for-mac'],
  'free-video-editing-software-for-mac': ['video-editing-software-for-mac', 'easy-video-editing-software-for-mac', 'professional-video-editing-software-for-mac', 'how-to-clear-ram-on-mac'],
  'professional-video-editing-software-for-mac': ['video-editing-software-for-mac', 'free-video-editing-software-for-mac', 'easy-video-editing-software-for-mac'],
  'easy-video-editing-software-for-mac': ['video-editing-software-for-mac', 'free-video-editing-software-for-mac', 'professional-video-editing-software-for-mac'],
  'house-construction-cost-guide': ['construction-estimate-quote-guide', 'brick-calculation-guide', 'flooring-calculation-guide'],
  'water-tank-size-capacity-guide': ['house-construction-cost-guide', 'gravel-calculation-guide'],
  'how-to-calculate-roof-area': ['house-construction-cost-guide', 'construction-estimate-quote-guide'],
  'flooring-calculation-guide': ['brick-calculation-guide', 'house-construction-cost-guide', 'construction-estimate-quote-guide'],
  'asphalt-calculation-guide': ['gravel-calculation-guide', 'construction-estimate-quote-guide'],
  'gravel-calculation-guide': ['asphalt-calculation-guide', 'construction-estimate-quote-guide'],
  'electricity-cost-calculation-guide': ['house-construction-cost-guide'],
  'brick-calculation-guide': ['house-construction-cost-guide', 'construction-estimate-quote-guide', 'flooring-calculation-guide'],
  'dimensional-weight-guide': ['json-formatting-guide'],
  'construction-estimate-quote-guide': ['house-construction-cost-guide', 'brick-calculation-guide', 'flooring-calculation-guide'],
  'base64-encoding-guide': ['jwt-decoding-guide', 'json-formatting-guide'],
  'jwt-decoding-guide': ['base64-encoding-guide', 'json-formatting-guide'],
  'json-formatting-guide': ['jwt-decoding-guide', 'base64-encoding-guide'],
  'heart-rate-zones-guide': ['calorie-deficit-guide', 'bmr-tdee-guide'],
  'how-to-calculate-emi': ['how-to-calculate-sip-returns', 'ppf-vs-fd-comparison'],
  'word-to-cdr-formatting-guide': ['pdf-to-cdr-editing-guide', 'preserve-fonts-coreldraw-conversion', 'best-coreldraw-print-format'],
  'pdf-to-cdr-editing-guide': ['eps-vs-cdr-guide', 'word-to-cdr-formatting-guide', 'svg-vs-cdr-guide'],
  'raster-image-to-cdr-guide': ['svg-vs-cdr-guide', 'open-cdr-without-coreldraw', 'best-coreldraw-print-format'],
  'svg-vs-cdr-guide': ['eps-vs-cdr-guide', 'pdf-to-cdr-editing-guide', 'best-coreldraw-print-format'],
  'open-cdr-without-coreldraw': ['newer-cdr-older-coreldraw', 'pdf-to-cdr-editing-guide', 'svg-vs-cdr-guide'],
  'newer-cdr-older-coreldraw': ['open-cdr-without-coreldraw', 'best-coreldraw-print-format', 'preserve-fonts-coreldraw-conversion'],
  'best-coreldraw-print-format': ['eps-vs-cdr-guide', 'svg-vs-cdr-guide', 'preserve-fonts-coreldraw-conversion'],
  'preserve-fonts-coreldraw-conversion': ['word-to-cdr-formatting-guide', 'pdf-to-cdr-editing-guide', 'best-coreldraw-print-format'],
  'psd-to-html-conversion-guide': ['psd-to-responsive-html', 'psd-to-html-email'],
  'psd-to-html-email': ['psd-to-html-conversion-guide', 'psd-to-responsive-html'],
  'psd-to-responsive-html': ['psd-to-html-conversion-guide', 'psd-to-html-email'],
  'step-to-3d-pdf-conversion-guide': ['pdf-security-guide', 'pdf-compression-guide', 'best-coreldraw-print-format'],
  'rgb-vs-cmyk-for-printing': ['print-bleed-trim-safe-area-guide', 'image-formats-guide', 'best-coreldraw-print-format'],
  'print-bleed-trim-safe-area-guide': ['rgb-vs-cmyk-for-printing', 'best-coreldraw-print-format', 'pdf-security-guide'],
  'eps-vs-cdr-guide': ['pdf-to-cdr-editing-guide', 'svg-vs-cdr-guide', 'best-coreldraw-print-format'],
  'how-to-save-a-screenshot-as-a-pdf': ['how-to-merge-pdf-files', 'pdf-security-guide', 'image-formats-guide'],
  'how-to-clear-ram-on-mac': ['free-video-editing-software-for-mac'],
};

