// Comprehensive icon mapping for all tools
export const toolIcons: Record<string, string> = {
  // ====== PDF TOOLS ======
  'add-image-to-pdf': '📄',
  'add-page-numbers': '🔢',
  'add-watermark': '💧',
  'compress-pdf': '📦',
  'crop-pdf': '✂️',
  'delete-pdf-pages': '🗑️',
  'extract-pdf-pages': '📤',
  'extract-pdf-text': '📝',
  'flatten-pdf': '📋',
  'interleave-pdf': '🔄',
  'jpg-to-pdf': '🖼️',
  'merge-pdf': '📑',
  'pdf-metadata-editor': '🏷️',
  'pdf-to-image': '🖼️',
  'pdf-to-jpg': '🖼️',
  'pdf-tools': '📄',
  'protect-pdf': '🔒',
  'reorder-pdf': '🔀',
  'rotate-pdf': '🔄',
  'sign-pdf': '✍️',
  'split-pdf': '✂️',
  'unlock-pdf': '🔓',
  'webp-to-pdf': '🖼️',

  // ====== IMAGE TOOLS ======
  'batch-image-converter': '🔄',
  'blur-face': '🎭',
  'change-image-resolution': '📐',
  'color-extraction-studio': '🎨',
  'compress-image': '📦',
  'compress-jpg': '📦',
  'compress-png': '📦',
  'compress-webp': '📦',
  'convert-jpg-to-png': '🔄',
  'convert-jpg-to-webp': '🔄',
  'convert-png-to-jpg': '🔄',
  'convert-png-to-webp': '🔄',
  'convert-webp-to-jpg': '🔄',
  'crop-image': '✂️',
  'heic-to-jpg': '🔄',
  'heic-to-png': '🔄',
  'html-to-image': '🌐',
  'icon-sticker-maker': '🎯',
  'id-photo-maker': '🪪',
  'image-converter': '🔄',
  'image-dpi-converter': '📐',
  'image-metadata-viewer': '🏷️',
  'image-tools': '🖼️',
  'image-to-pdf': '🖼️',
  'meme-generator': '😂',
  'photo-collage-maker': '🖼️',
  'photo-editor': '✏️',
  'png-to-svg': '🔄',
  'resize-image': '📐',
  'rotate-image': '🔄',
  'social-media-resizer': '📱',
  'svg-to-png': '🔄',
  'upscale-image': '🔍',
  'watermark-image': '💧',
  'webp-to-png': '🔄',

  // ====== FINANCE TOOLS ======
  'sip-calculator': '📈',
  'loan-emi-calculator': '🏠',
  'gst-calculator': '🧾',
  'tax-calculator': '📋',
  'ppf-calculator': '🏦',
  'fd-calculator': '🏛️',
  'currency-converter': '💱',
  'retirement-calculator': '🐷',
  'cashflow-budget-architect': '💰',
  'investment-return-profiler': '📈',
  'loan-amortization-suite': '📊',
  'savings-retirement-hub': '💰',
  'wealth-inflation-matrix': '📈',
  'taxation-compliance-deck': '📋',

  // ====== HEALTH TOOLS ======
  'bmi-calculator': '⚖️',
  'bmr-calculator': '🔥',
  'body-fat-calculator': '📊',
  'calorie-calculator': '🍎',
  'calories-burned-calculator': '🏃',
  'healthy-weight-calculator': '⚖️',
  'heart-rate-calculator': '❤️',
  'ideal-weight-calculator': '⚖️',
  'lean-body-mass-calculator': '💪',
  'running-calories-calculator': '🏃',
  'target-heart-rate-calculator': '❤️',
  'tdee-calculator': '🔥',
  'waist-to-height-ratio-calculator': '📏',
  'waist-to-hip-ratio-calculator': '📏',
  'walking-calories-calculator': '🚶',

  // ====== DEVELOPER TOOLS ======
  'base64-encoder': '🔐',
  'code-minifier-beautifier': '💻',
  'developer-tools': '💻',
  'developer-utils': '🛠️',
  'jwt-base64-deck': '🔑',
  'markup-formatter': '📝',
  'universal-json-studio': '📋',
  'web-crypto-studio': '🔒',
  'webmaster-seo-builder': '🔍',
  'bioluminescent-reader': '🧬',
  'qr-code-studio': '📱',

  // ====== CONSTRUCTION TOOLS ======
  'concrete-calculator': '🏗️',
  'brick-calculator': '🧱',
  'construction-calculators': '🔨',
};

export const getToolIcon = (slug: string): string => {
  if (toolIcons[slug]) return toolIcons[slug];
  for (const [key, icon] of Object.entries(toolIcons)) {
    if (slug.includes(key)) return icon;
  }
  return '🔧';
};
