// Comprehensive icon mapping for all tools
export const toolIcons: Record<string, string> = {
  // ====== AUTO-AUDITED TOOL ICONS ======
  'css-gradient-generator': '🎨',
  'developer-utilities': '🛠️',
  'finance-calculators': '🛠️',
  'health-calculators': '🛠️',
  'meta-tag-generator': '🔍',
  'regex-tester': '🔤',
  'robots-txt-generator': '🤖',
  'unix-timestamp-converter': '🕒',
  'utm-builder': '🔗',
  'uuid-generator': '🆔',

  // ====== PDF TOOLS ======
  'add-image-to-pdf': '📄',
  'add-page-numbers': '🔢',
  'add-watermark': '💧',
  'compress-pdf': '📦',
  'crop-pdf': '✂️',
  'delete-pdf-pages': '🗑️',
  'extract-pdf-pages': '📤',
  'extract-pdf-text': '📝',
  'flatten-pdf': '📋',
  'interleave-pdf': '🔄',
  'jpg-to-pdf': '🖼️',
  'merge-pdf': '📑',
  'pdf-metadata-editor': '🏷️',
  'pdf-to-image': '🖼️',
  'pdf-to-jpg': '🖼️',
  'pdf-tools': '📄',
  'protect-pdf': '🔒',
  'reorder-pdf': '🔀',
  'rotate-pdf': '🔄',
  'sign-pdf': '✍️',
  'split-pdf': '✂️',
  'unlock-pdf': '🔓',
  'webp-to-pdf': '🖼️',

  // ====== IMAGE TOOLS ======
  'batch-image-converter': '🔄',
  'blur-face': '🎭',
  'change-image-resolution': '📐',
  'image-color-picker': '🎨',
  'compress-image': '📦',
  'compress-jpg': '📦',
  'compress-png': '📦',
  'compress-webp': '📦',
  'convert-jpg-to-png': '🔄',
  'convert-jpg-to-webp': '🔄',
  'convert-png-to-jpg': '🔄',
  'convert-png-to-webp': '🔄',
  'convert-webp-to-jpg': '🔄',
  'crop-image': '✂️',
  'heic-to-jpg': '🔄',
  'heic-to-png': '🔄',
  'html-to-image': '🌐',
  'icon-sticker-maker': '🎯',
  'id-photo-maker': '🪪',
  'image-converter': '🔄',
  'image-dpi-converter': '📐',
  'image-metadata-viewer': '🏷️',
  'image-tools': '🖼️',
  'image-to-pdf': '🖼️',
  'meme-generator': '😂',
  'photo-collage-maker': '🖼️',
  'photo-editor': '✏️',
  'png-to-svg': '🔄',
  'resize-image': '📐',
  'rotate-image': '🔄',
  'social-media-resizer': '📱',
  'svg-to-png': '🔄',
  'upscale-image': '🔍',
  'watermark-image': '💧',
  'webp-to-png': '🔄',

  // ====== FINANCE TOOLS ======
  'sip-calculator': '📈',
  'loan-emi-calculator': '🏠',
  'gst-calculator': '🧾',
  'tax-calculator': '📋',
  'ppf-calculator': '🏦',
  'fd-calculator': '🏛️',
  'currency-converter': '💱',
  'retirement-calculator': '🐷',
  'cashflow-budget-architect': '💰',
  'investment-return-profiler': '📈',
  'loan-amortization-suite': '📊',
  'savings-retirement-hub': '💰',
  'wealth-inflation-matrix': '📈',
  'taxation-compliance-deck': '📋',

  // ====== HEALTH TOOLS ======
  'bmi-calculator': '⚖️',
  'bmr-calculator': '🔥',
  'body-fat-calculator': '📊',
  'calorie-calculator': '🍎',
  'calories-burned-calculator': '🏃',
  'healthy-weight-calculator': '⚖️',
  'heart-rate-calculator': '❤️',
  'ideal-weight-calculator': '⚖️',
  'lean-body-mass-calculator': '💪',
  'running-calories-calculator': '🏃',
  'tdee-calculator': '🔥',
  'waist-to-height-ratio-calculator': '📏',
  'waist-to-hip-ratio-calculator': '📏',
  'walking-calories-calculator': '🚶',

  // ====== DEVELOPER TOOLS ======
  'cidr-subnet-wildcard-calculator': '🌐',
  'csv-to-json-converter': '📥',
  'json-diff-compare': '🔀',
  'url-encoder-decoder': '🔗',
  'html-entity-encoder-decoder': '🏷️',
  'json-schema-validator': '✅',
  'ip-range-calculator': '📡',
  'vlsm-subnet-calculator': '🧩',
  'mac-address-generator': '🪪',
  'cron-next-run-calculator': '📅',
  'http-status-code-lookup': '🚦',
  'json-to-csv-flattener': '📊',
  'aws-glacier-retrieval-calculator': '🧊',
  'base64-encoder': '🔐',
  'xml-to-word-converter': '📄',
  'word-to-xml-converter': '🧾',
  'code-minifier-beautifier': '💻',
  'developer-tools': '💻',
  'developer-utils': '🛠️',
  'jwt-decoder': '🔑',
  'markup-formatter': '📝',
  'json-formatter': '📋',
  'web-crypto-studio': '🔒',
  'webmaster-seo-builder': '🔍',
  'bioluminescent-reader': '🧬',
  'qr-code-generator': '📱',

  // ====== EVERYDAY TOOLS ======
  'everyday-calculators': '🌟',
  'fuel-cost-split-calculator': '⛽',
  'barbell-plate-calculator': '🏋️',
  'aquarium-volume-calculator': '🐠',
  'tire-size-calculator': '🛞',
  'dimensional-weight-calculator': '📦',
  'electricity-cost-calculator': '⚡',
  'unit-price-calculator': '🏷️',

  // ====== NEW DEVELOPER TOOLS ======
  'aspect-ratio-padding-calculator': '📐',
  'cron-expression-humanizer': '⏰',
  'css-clamp-font-generator': '🔤',

  // ====== CONSTRUCTION TOOLS - ALL 20 ======
  'asphalt-calculator': '🛣️',
  'brick-calculator': '🧱',
  'board-foot-calculator': '🪵',
  'cement-calculator': '🏗️',
  'concrete-calculator': '🏗️',
  'construction-cost-calculator': '💰',
  'construction-estimate-builder': '🧾',
  'contractor-estimate-generator': '📋',
  'construction-calculators': '🔨',
  'air-compressor-cfm-calculator': '💨',
  'ladder-safe-reach-calculator': '🪜',
  'saw-kerf-calculator': '🪚',
  'osha-portable-toilet-calculator': '🚻',
  'egress-window-code-checker': '🪟',
  'dumpster-weight-calculator': '🗑️',
  'roof-pitch-calculator': '📐',
  'stair-stringer-calculator': '🪜',
  'deck-board-calculator': '🪵',
  'fence-calculator': '🚧',
  'post-hole-concrete-calculator': '🕳️',
  'drywall-calculator': '🧱',
  'paver-calculator': '🧱',
  'polymeric-sand-calculator': '⌛',
  'mulch-calculator': '🌿',
  'topsoil-calculator': '🌱',
  'excavation-calculator': '🚜',
  'flooring-calculator': '🏠',
  'gravel-calculator': '🪨',
  'house-construction-cost-calculator': '🏠',
  'land-area-converter': '📐',
  'paint-calculator': '🎨',
  'rebar-calculator': '🔩',
  'roof-area-calculator': '🏠',
  'sand-calculator': '🏖️',
  'solar-panel-calculator': '☀️',
  'steel-weight-calculator': '🔩',
  'tile-calculator': '🧱',
  'voltage-drop-calculator': '⚡',
  'wallpaper-calculator': '🧻',
  'water-tank-calculator': '💧',
  'wire-size-calculator': '🔌',
  'ai-token-calculator': '🧠',
  'llm-api-cost-calculator': '💬',
  'gpu-compute-cost-calculator': '🖥️',
  'cloud-hosting-cost-calculator': '☁️',
  'cdn-cost-calculator': '🌐',
  'startup-runway-calculator': '🛫',
  'saas-burn-rate-calculator': '🔥',
  'ltv-cac-ratio-calculator': '⚖️',
  'cac-payback-calculator': '⏱️',
  'churn-impact-calculator': '📉',
  'rule-of-40-calculator': '4️⃣',
  'net-revenue-retention-calculator': '🔁',
  'rental-property-cash-flow-calculator': '🏘️',
  'rental-yield-calculator': '🏡',
  'cap-rate-calculator': '🏢',
  'cash-on-cash-return-calculator': '💵',
  'brrrr-calculator': '♻️',
  'fix-and-flip-profit-calculator': '🔨',
  'drawdown-recovery-calculator': '📈',
  'debt-snowball-vs-avalanche-calculator': '🏔️',
};

export const getToolIcon = (slug: string): string => {
  if (toolIcons[slug]) return toolIcons[slug];
  for (const [key, icon] of Object.entries(toolIcons)) {
    if (slug.includes(key)) return icon;
  }
  return '🔧';
};
