// Tool descriptions for SEO optimization
export const toolDescriptions: Record<string, string> = {
  // PDF Tools
  'add-image-to-pdf': 'Add images to PDF documents instantly. Insert JPG, PNG, WebP, and other images into any PDF file online.',
  'add-page-numbers': 'Add sequential page numbers with a chosen starting number and position.',
  'add-watermark': 'Add a centered diagonal text watermark to every PDF page locally.',
  'compress-pdf': 'Compress PDF files online for free. Reduce PDF file size without losing quality.',
  'merge-pdf': 'Merge PDF files online for free. Combine multiple PDF documents into one.',
  'split-pdf': 'Split PDF files online for free. Extract specific pages or split PDF into multiple documents.',
  'protect-pdf': 'Temporarily unavailable while genuine browser-based PDF encryption is being validated.',
  'sign-pdf': 'Draw and place a visible handwritten signature image on one PDF page locally.',
  'crop-pdf': 'Set custom crop-box margins on every PDF page locally in your browser.',
  'delete-pdf-pages': 'Delete unwanted pages from PDF documents online free. Remove specific pages instantly.',
  'extract-pdf-pages': 'Extract specific pages from PDF documents online free. Save selected pages as separate PDF files.',
  'extract-pdf-text': 'Extract text from PDF documents online free. Get editable text content from PDF files.',
  'flatten-pdf': 'Flatten supported interactive PDF form fields into static page content.',
  'reorder-pdf': 'Reorder PDF pages online for free. Change page order in your PDF documents easily.',
  'rotate-pdf': 'Rotate pages in PDF documents online free. Correct page orientation in your PDF files.',
  'unlock-pdf': 'Temporarily unavailable while genuine browser-based PDF decryption is being validated.',
  'pdf-to-image': 'Convert PDF pages to images online free. Transform each page of your PDF into separate images.',
  'pdf-to-jpg': 'Convert PDF pages to JPG images online free. Transform PDF documents into high-quality JPG images.',
  'jpg-to-pdf': 'Convert JPG images to PDF documents online free. Transform your JPG files into professional PDF files.',
  'interleave-pdf': 'Alternate pages from two PDFs in A1, B1, A2, B2 order.',
  'image-to-pdf': 'Convert images to PDF documents online free. Combine JPG, PNG, and WebP images into a single PDF file.',
  'webp-to-pdf': 'Convert WebP images to PDF documents online free. Transform modern WebP files into professional PDF documents.',
  
  // Image Tools
  'resize-image': 'Resize images online for free. Change image dimensions, scale photos, and optimize for web.',
  'compress-jpg': 'Re-encode JPEG images with adjustable lossy quality locally in your browser.',
  'compress-webp': 'Re-encode WebP images with adjustable browser quality and local processing.',
  'compress-image': 'Re-encode JPEG and WebP with adjustable quality, or convert PNG to compressed WebP locally.',
  'crop-image': 'Crop images online for free. Cut, trim, and crop photos to any dimensions.',
  'rotate-image': 'Rotate images online for free. Flip, mirror, and straighten your images easily.',
  'image-converter': 'Convert JPG, PNG, and WebP images locally with previews and format-aware quality controls.',
  'png-to-svg': 'Temporarily unavailable pending a genuine raster-to-vector tracing engine.',
  'svg-to-png': 'Rasterize a browser-compatible SVG at its intrinsic dimensions and export PNG.',
  'webp-to-png': 'Convert WebP images to PNG online free. Transform modern WebP files to transparent PNG format.',
  'heic-to-jpg': 'Convert HEIC files to JPG online free. Transform Apple HEIC images to widely-supported JPG format.',
  'heic-to-png': 'Convert HEIC files to PNG online free. Transform Apple HEIC images to transparent PNG format.',
  'html-to-image': 'Temporarily unavailable pending a safe, deterministic HTML rendering engine.',
  'upscale-image': 'Enlarge images by 2×, 3×, or 4× using high-quality browser interpolation.',
  'blur-face': 'Temporarily unavailable until validated on-device face detection is added.',
  'batch-image-converter': 'Convert multiple images at once online free. Batch convert JPG, PNG, WebP, and HEIC formats.',
  'change-image-resolution': 'Resize an image to a standard HD, FHD, QHD, UHD, or square pixel preset.',
  'image-color-picker': 'Pick one image pixel and copy its exact hexadecimal RGB color locally.',
  'icon-sticker-maker': 'Create custom icons and stickers from images online free. Design unique stickers and icons.',
  'id-photo-maker': 'Crop a photo into convenient ID-size pixel presets with zoom and position controls.',
  'social-media-resizer': 'Fit or crop images into built-in social-media pixel presets with local PNG export.',
  'watermark-image': 'Add customizable text, color, opacity, and position to an image with local PNG export.',
  'convert-png-to-webp': 'Convert a still PNG to browser-encoded WebP locally.',
  'convert-webp-to-jpg': 'Convert a still WebP to JPEG with transparent areas filled white.',
  'photo-editor': 'Edit photos online with professional tools. Crop, resize, adjust colors, and apply filters.',
  'photo-collage-maker': 'Create a local PNG grid collage from up to 12 supported images.',
  'meme-generator': 'Create custom memes from images instantly online free. Add text, captions, and effects.',
  'image-metadata-viewer': 'View file properties and decoded pixel dimensions locally; EXIF is not parsed.',
  'image-dpi-converter': 'Temporarily unavailable pending verified density-metadata writers.',
  
  // Finance Tools
  'sip-calculator': 'Calculate Systematic Investment Plan (SIP) returns online free. Plan your mutual fund investments.',
  'loan-emi-calculator': 'Calculate monthly EMI for home, car, and personal loans online free. Plan your loan repayments.',
  'fd-calculator': 'Calculate Fixed Deposit returns and maturity amount online free. Plan your FD investments.',
  'ppf-calculator': 'Calculate Public Provident Fund (PPF) returns online free. Plan your PPF investments.',
  'gst-calculator': 'Calculate GST amounts and exclusive/inclusive prices online free. Get accurate GST calculations.',
  'tax-calculator': 'Estimate AY 2026–27 Indian income tax under the new regime with rebate, marginal relief, and cess.',
  'retirement-calculator': 'Plan your retirement corpus with inflation-adjusted projections online free.',
  'investment-return-calculator': 'Calculate investment returns with compound growth projections online free.',
  'inflation-calculator': 'Calculate how inflation erodes your money\'s value over time online free.',
  'budget-calculator': 'Plan your monthly budget, track expenses, and manage cash flow effectively online free.',
  'currency-converter': 'Convert major currencies using dated ECB reference exchange rates.',
  'loan-amortization-suite': 'Calculate loan amortization schedules online free. Plan your loan payments.',
  'cashflow-budget-architect': 'Plan your monthly budget, track expenses, and manage cash flow effectively.',
  'savings-retirement-hub': 'Plan your savings and retirement online free. Calculate how much you need to save.',
  'wealth-inflation-matrix': 'Calculate how inflation erodes your money\'s value over time online free.',
  'taxation-compliance-deck': 'Calculate income tax, GST, and compliance requirements online free.',
  
  // Health Tools
  'bmi-calculator': 'Calculate your Body Mass Index (BMI) online free. Get health category assessment.',
  'bmr-calculator': 'Calculate your Basal Metabolic Rate (BMR) online free. Understand your daily calorie needs.',
  'tdee-calculator': 'Calculate your Total Daily Energy Expenditure (TDEE) online free.',
  'body-fat-calculator': 'Estimate your body fat percentage online free. Track fitness progress.',
  'ideal-weight-calculator': 'Calculate your ideal body weight based on height and age online free.',
  'healthy-weight-calculator': 'Calculate your healthy weight range based on height and age online free.',
  'calorie-calculator': 'Calculate daily calorie needs for weight management online free.',
  'calories-burned-calculator': 'Estimate calories burned during exercise and daily activities online free.',
  'running-calories-calculator': 'Calculate calories burned while running online free.',
  'walking-calories-calculator': 'Calculate calories burned while walking online free.',
  'heart-rate-calculator': 'Calculate your target heart rate zones for exercise online free.',
  'target-heart-rate-calculator': 'Calculate target heart rate zones for optimal fitness online free.',
  'waist-to-height-ratio-calculator': 'Calculate your waist-to-height ratio instantly online free.',
  'waist-to-hip-ratio-calculator': 'Calculate your waist-to-hip ratio accurately online free.',
  'lean-body-mass-calculator': 'Calculate your lean body mass and muscle content online free.',
  
  // Developer Tools
  'qr-code-generator': 'Generate colored QR codes or decode a QR code from an uploaded image locally.',
  'jwt-decoder': 'Decode JWT header and payload JSON locally without verifying the token signature.',
  'json-formatter': 'View, edit, and format JSON data online free. Parse and validate JSON.',
  'base64-encoder': 'Encode UTF-8 text to Base64 or decode Base64 back to UTF-8 text locally.',
  'code-minifier-beautifier': 'Temporarily unavailable pending parser-backed code processing.',
  'markup-formatter': 'Temporarily unavailable pending grammar-aware formatters.',
  'web-crypto-studio': 'Generate SHA-256 hashes, random passwords, and UUID v4 identifiers locally.',
  'webmaster-seo-builder': 'Generate UTM URLs, basic social meta tags, and a simple robots.txt block locally.',
  'developer-utilities': 'Compatibility redirect to the Developer Tools category.',
  
  // Construction Tools
  'concrete-calculator': 'Calculate concrete volume needed for slabs, footings, and columns online free.',
  'cement-calculator': 'Calculate exact cement bags needed for your concrete work online free.',
  'brick-calculator': 'Calculate the number of bricks needed for your construction project online free.',
  'steel-weight-calculator': 'Calculate weight of steel bars, beams, and structural steel online free.',
  'rebar-calculator': 'Calculate rebar quantity and weight for reinforced concrete structures online free.',
  'construction-cost-calculator': 'Calculate total construction costs including materials, labor, overhead online free.',
  'house-construction-cost-calculator': 'Estimate house building costs per square foot online free.',
  'sand-calculator': 'Calculate sand volume and weight for construction projects online free.',
};
