// SEO-optimized descriptions for all tools
export const toolDescriptions: Record<string, string> = {
  // PDF Tools
  'add-image-to-pdf': 'Add images to PDF files easily. Combine JPG, PNG, or WebP images into a single PDF document online for free.',
  'add-page-numbers': 'Add page numbers to PDF documents automatically. Customize position, format, and starting number for professional results.',
  'add-watermark': 'Add text or image watermarks to PDF files. Protect your documents with custom watermarks easily online.',
  'base64-encoder': 'Encode text or files to Base64 format. Decode Base64 strings back to original text instantly in your browser.',
  'batch-image-converter': 'Convert multiple images at once. Batch convert JPG, PNG, WebP, and HEIC formats quickly and efficiently.',
  'bioluminescent-reader': 'Read and analyze bioluminescent data. Process light emission measurements for research and analysis.',
  'blur-face': 'Blur faces in images automatically. Protect privacy by detecting and blurring faces in photos online.',
  'bmi-calculator': 'Calculate your Body Mass Index (BMI) instantly. Get health category assessment and weight management recommendations.',
  'bmr-calculator': 'Calculate your Basal Metabolic Rate (BMR) daily calorie needs. Understand your body\'s energy requirements at rest.',
  'body-fat-calculator': 'Estimate your body fat percentage using multiple methods. Track fitness progress with accurate body composition analysis.',
  'brick-calculator': 'Calculate the number of bricks needed for your construction project. Estimate materials for walls and structures accurately.',
  'calorie-calculator': 'Calculate daily calorie needs for weight management. Get personalized calorie targets for your fitness goals.',
  'calories-burned-calculator': 'Estimate calories burned during exercise and daily activities. Track workout calorie expenditure accurately.',
  'change-image-resolution': 'Change image resolution and dimensions online. Resize images to specific pixel dimensions without quality loss.',
  'code-minifier-beautifier': 'Minify or beautify JavaScript, CSS, and HTML code. Optimize your code for production or make it readable.',
  'color-extraction-studio': 'Extract colors from images easily. Generate color palettes and get hex codes from any image online.',
  'compress-image': 'Compress images online while maintaining quality. Reduce file size for faster loading and sharing.',
  'compress-jpg': 'Compress JPG images online with adjustable quality. Balance file size and image quality for optimal results.',
  'compress-pdf': 'Compress PDF files online without losing quality. Reduce PDF file size for email, web, and sharing.',
  'compress-png': 'Compress PNG images online without losing quality. Reduce PNG file size for web and mobile applications.',
  'compress-webp': 'Compress WebP images online efficiently. Reduce WebP file size while maintaining visual quality.',
  'concrete-calculator': 'Calculate concrete volume needed for slabs, footings, and columns. Estimate materials for your construction project.',
  'convert-jpg-to-png': 'Convert JPG images to PNG online for free. Transform your JPG files to transparent PNG format instantly.',
  'convert-jpg-to-webp': 'Convert JPG images to WebP online. Create smaller, faster-loading WebP images from JPG files.',
  'convert-png-to-jpg': 'Convert PNG images to JPG online. Transform PNG files with transparency to compressed JPG format.',
  'convert-png-to-webp': 'Convert PNG images to WebP online. Create smaller, modern WebP images from PNG files.',
  'convert-webp-to-jpg': 'Convert WebP images to JPG online. Transform modern WebP files to widely-supported JPG format.',
  'crop-image': 'Crop images online with precision. Cut, trim, and resize images to exact dimensions easily.',
  'crop-pdf': 'Crop PDF pages online. Trim margins and crop content from PDF documents with precision.',
  'currency-converter': 'Convert currencies using real-time exchange rates. Get accurate international currency conversions instantly.',
  'delete-pdf-pages': 'Delete unwanted pages from PDF documents. Remove specific pages from your PDF files online.',
  'extract-pdf-pages': 'Extract specific pages from PDF documents. Save selected pages as separate PDF files easily.',
  'extract-pdf-text': 'Extract text from PDF documents online. Get editable text content from PDF files instantly.',
  'fd-calculator': 'Calculate Fixed Deposit returns and maturity amount. Plan your FD investments with accurate interest calculations.',
  'flatten-pdf': 'Flatten PDF files permanently. Remove editable fields and make PDFs non-editable with simple flattening.',
  'gst-calculator': 'Calculate GST amounts and exclusive/inclusive prices. Get accurate GST calculations for your business transactions.',
  'healthy-weight-calculator': 'Calculate your healthy weight range based on height and age. Get personalized weight recommendations.',
  'heart-rate-calculator': 'Calculate your target heart rate zones for exercise. Optimize your workout intensity for better results.',
  'heic-to-jpg': 'Convert HEIC files to JPG online. Transform Apple HEIC images to widely-supported JPG format.',
  'heic-to-png': 'Convert HEIC files to PNG online. Transform Apple HEIC images to transparent PNG format.',
  'html-to-image': 'Convert HTML code to images online. Render HTML as JPG, PNG, or WebP images instantly.',
  'icon-sticker-maker': 'Create custom icons and stickers from images. Design unique stickers and icons for your projects.',
  'id-photo-maker': 'Create professional ID photos online. Make passport, visa, and ID photos with correct dimensions.',
  'ideal-weight-calculator': 'Calculate your ideal body weight based on height and age. Get personalized weight recommendations.',
  'image-converter': 'Convert images between JPG, PNG, WebP, and more. Transform your images to any format online.',
  'image-dpi-converter': 'Convert image DPI and resolution online. Adjust image density for print and digital use.',
  'image-metadata-viewer': 'View and extract image metadata. See EXIF data, camera settings, and image details online.',
  'image-to-pdf': 'Convert images to PDF documents. Combine JPG, PNG, and WebP images into a single PDF file.',
  'interleave-pdf': 'Interleave pages from multiple PDF documents. Alternate pages from two PDFs into one document.',
  'investment-return-calculator': 'Calculate investment returns with compound growth projections. Plan your investment strategy with detailed financial analysis.',
  'jpg-to-pdf': 'Convert JPG images to PDF documents. Transform your JPG files into professional PDF files.',
  'jwt-decoder': 'Decode JWT tokens instantly in your browser. Parse JSON Web Tokens and view decoded payload securely.',
  'lean-body-mass-calculator': 'Calculate your lean body mass and muscle content. Understand your body composition accurately.',
  'loan-amortization-suite': 'Calculate loan amortization schedules. Plan your loan payments with detailed amortization tables.',
  'loan-emi-calculator': 'Calculate monthly EMI for home, car, and personal loans. Plan your loan repayments accurately.',
  'markup-formatter': 'Format HTML, XML, and markup code for readability. Clean and format your markup code online.',
  'meme-generator': 'Create custom memes from images instantly. Add text, captions, and effects to create viral memes.',
  'merge-pdf': 'Merge multiple PDF files into one document. Combine PDF files easily online without uploading.',
  'pdf-metadata-editor': 'Edit PDF document metadata and properties. View and modify PDF file information online.',
  'pdf-to-image': 'Convert PDF pages to images online. Transform each page of your PDF into separate images.',
  'pdf-to-jpg': 'Convert PDF pages to JPG images online. Transform PDF documents into high-quality JPG images.',
  'photo-collage-maker': 'Create custom photo collages from your images. Design beautiful collages with multiple photos.',
  'photo-editor': 'Edit photos online with professional tools. Crop, resize, adjust colors, and apply filters easily.',
  'png-to-svg': 'Convert PNG images to SVG vectors online. Create scalable SVG graphics from PNG images.',
  'ppf-calculator': 'Calculate Public Provident Fund (PPF) returns. Plan your PPF investments with accurate calculations.',
  'protect-pdf': 'Protect PDF documents with passwords. Add encryption and security to your PDF files online.',
  'qr-code-studio': 'Create custom QR codes from any URL or text. Design branded QR codes for business and personal use.',
  'reorder-pdf': 'Reorder and rearrange PDF pages quickly. Change page order in your PDF documents easily.',
  'resize-image': 'Resize images online with precision. Scale images to exact dimensions without losing quality.',
  'retirement-calculator': 'Plan your retirement corpus with inflation-adjusted projections. Calculate how much you need to save for retirement.',
  'rotate-image': 'Rotate images online in any direction. Flip, mirror, and straighten your images easily.',
  'rotate-pdf': 'Rotate pages in PDF documents. Correct page orientation in your PDF files online.',
  'running-calories-calculator': 'Calculate calories burned while running. Track your running calorie expenditure accurately.',
  'sand-calculator': 'Calculate sand volume and weight for construction. Estimate materials for your building project.',
  'sign-pdf': 'Sign PDF documents electronically. Add digital signatures to PDF files online securely.',
  'sip-calculator': 'Calculate Systematic Investment Plan (SIP) returns. Plan your mutual fund investments with accurate projections.',
  'social-media-resizer': 'Resize images for social media platforms. Create perfect images for Instagram, Facebook, Twitter, and more.',
  'split-pdf': 'Split PDF documents into multiple files. Extract pages or split PDF into separate files online.',
  'steel-weight-calculator': 'Calculate steel weight for bars, beams, and structural steel. Estimate steel materials for construction projects.',
  'svg-to-png': 'Convert SVG images to PNG online. Transform scalable SVG files to PNG format instantly.',
  'target-heart-rate-calculator': 'Calculate target heart rate zones for optimal fitness. Train effectively with heart rate monitoring.',
  'tax-calculator': 'Calculate income tax, GST, and compliance requirements. Get accurate tax calculations for individuals and businesses.',
  'tdee-calculator': 'Calculate your Total Daily Energy Expenditure (TDEE). Understand your complete daily calorie requirements.',
  'universal-json-studio': 'View, edit, and format JSON data online. Parse and validate JSON with powerful editing tools.',
  'unlock-pdf': 'Unlock password-protected PDF documents. Remove PDF passwords and security restrictions online.',
  'upscale-image': 'Upscale images online using AI. Enlarge images without losing quality using advanced upscaling technology.',
  'waist-to-height-ratio-calculator': 'Calculate your waist-to-height ratio instantly. Assess your health risk with WHtR measurement.',
  'waist-to-hip-ratio-calculator': 'Calculate your waist-to-hip ratio accurately. Assess body fat distribution and health risks.',
  'walking-calories-calculator': 'Calculate calories burned while walking. Track your walking exercise calorie expenditure.',
  'watermark-image': 'Add text or image watermarks to photos. Protect your images with custom watermarks online.',
  'web-crypto-studio': 'Encrypt, decrypt, hash, and sign data using Web Crypto API. Secure your data with modern cryptography.',
  'webmaster-seo-builder': 'Build SEO-friendly websites and content. Optimize your website for search engines effectively.',
  'webp-to-pdf': 'Convert WebP images to PDF documents. Transform modern WebP files into professional PDF documents.',
  'webp-to-png': 'Convert WebP images to PNG online. Transform modern WebP files to transparent PNG format.',
  
  // Construction tools (SEO optimized)
  'construction-cost-calculator': 'Calculate total construction costs including materials, labor, overhead, and contingency. Get accurate building estimates for your construction project.',
  'house-construction-cost-calculator': 'Estimate house building costs per square foot. Plan your residential construction budget with detailed cost breakdown.',
  'cement-calculator': 'Calculate exact cement bags needed for your concrete work. Estimate cement requirements with proper mix ratios for construction.',
  'rebar-calculator': 'Calculate rebar quantity and weight for reinforced concrete structures. Plan your reinforcement materials accurately.',
};
