// Tool descriptions for SEO optimization
export const toolDescriptions: Record<string, string> = {
  // PDF Tools
  'add-image-to-pdf': 'Add images to PDF documents instantly. Insert JPG, PNG, WebP, and other images into any PDF file online.',
  'add-page-numbers': 'Add page numbers to PDF documents automatically. Customize position, format, and starting number.',
  'add-watermark': 'Add text or image watermarks to PDF files online free. Protect your documents with custom watermarks.',
  'compress-pdf': 'Compress PDF files online for free. Reduce PDF file size without losing quality.',
  'merge-pdf': 'Merge PDF files online for free. Combine multiple PDF documents into one.',
  'split-pdf': 'Split PDF files online for free. Extract specific pages or split PDF into multiple documents.',
  'protect-pdf': 'Add password protection to PDF files online free. Secure your documents with encryption.',
  'sign-pdf': 'Sign PDF documents electronically online free. Add digital signatures to PDF files securely.',
  'crop-pdf': 'Crop PDF pages online for free. Trim margins and crop content from PDF documents.',
  'delete-pdf-pages': 'Delete unwanted pages from PDF documents online free. Remove specific pages instantly.',
  'extract-pdf-pages': 'Extract specific pages from PDF documents online free. Save selected pages as separate PDF files.',
  'extract-pdf-text': 'Extract text from PDF documents online free. Get editable text content from PDF files.',
  'flatten-pdf': 'Flatten PDF files permanently online free. Remove editable fields and make PDFs non-editable.',
  'reorder-pdf': 'Reorder PDF pages online for free. Change page order in your PDF documents easily.',
  'rotate-pdf': 'Rotate pages in PDF documents online free. Correct page orientation in your PDF files.',
  'unlock-pdf': 'Unlock password-protected PDF documents online free. Remove PDF passwords and security restrictions.',
  'pdf-to-image': 'Convert PDF pages to images online free. Transform each page of your PDF into separate images.',
  'pdf-to-jpg': 'Convert PDF pages to JPG images online free. Transform PDF documents into high-quality JPG images.',
  'jpg-to-pdf': 'Convert JPG images to PDF documents online free. Transform your JPG files into professional PDF files.',
  'interleave-pdf': 'Interleave pages from multiple PDF documents online free. Alternate pages from two PDFs into one document.',
  'image-to-pdf': 'Convert images to PDF documents online free. Combine JPG, PNG, and WebP images into a single PDF file.',
  'webp-to-pdf': 'Convert WebP images to PDF documents online free. Transform modern WebP files into professional PDF documents.',
  
  // Image Tools
  'resize-image': 'Resize images online for free. Change image dimensions, scale photos, and optimize for web.',
  'compress-image': 'Compress images online for free. Reduce image file size without losing quality.',
  'crop-image': 'Crop images online for free. Cut, trim, and crop photos to any dimensions.',
  'rotate-image': 'Rotate images online for free. Flip, mirror, and straighten your images easily.',
  'image-converter': 'Convert images between JPG, PNG, WebP, and more online free. Transform your images to any format.',
  'png-to-svg': 'Convert PNG images to SVG vectors online free. Create scalable SVG graphics from PNG images.',
  'svg-to-png': 'Convert SVG images to PNG online free. Transform scalable SVG files to PNG format.',
  'webp-to-png': 'Convert WebP images to PNG online free. Transform modern WebP files to transparent PNG format.',
  'heic-to-jpg': 'Convert HEIC files to JPG online free. Transform Apple HEIC images to widely-supported JPG format.',
  'heic-to-png': 'Convert HEIC files to PNG online free. Transform Apple HEIC images to transparent PNG format.',
  'html-to-image': 'Convert HTML code to images online free. Render HTML as JPG, PNG, or WebP images.',
  'upscale-image': 'Upscale images online using AI. Enlarge images without losing quality using advanced upscaling.',
  'blur-face': 'Blur faces in images automatically online free. Protect privacy by detecting and blurring faces.',
  'batch-image-converter': 'Convert multiple images at once online free. Batch convert JPG, PNG, WebP, and HEIC formats.',
  'change-image-resolution': 'Change image resolution and dimensions online free. Resize images to specific pixel dimensions.',
  'color-extraction-studio': 'Extract colors from images easily online free. Generate color palettes and get hex codes.',
  'icon-sticker-maker': 'Create custom icons and stickers from images online free. Design unique stickers and icons.',
  'id-photo-maker': 'Create professional passport, visa, and ID photos online free. Make ID photos with correct dimensions.',
  'social-media-resizer': 'Resize images for social media platforms online free. Create perfect images for Instagram, Facebook.',
  'watermark-image': 'Add text or image watermarks to photos online free. Protect your images with custom watermarks.',
  'photo-editor': 'Edit photos online with professional tools. Crop, resize, adjust colors, and apply filters.',
  'photo-collage-maker': 'Create custom photo collages from your images online free. Design beautiful collages.',
  'meme-generator': 'Create custom memes from images instantly online free. Add text, captions, and effects.',
  'image-metadata-viewer': 'View and extract image metadata online free. See EXIF data, camera settings, and image details.',
  'image-dpi-converter': 'Convert image DPI and resolution online free. Adjust image density for print and digital use.',
  
  // Finance Tools
  'sip-calculator': 'Calculate Systematic Investment Plan (SIP) returns online free. Plan your mutual fund investments.',
  'loan-emi-calculator': 'Calculate monthly EMI for home, car, and personal loans online free. Plan your loan repayments.',
  'fd-calculator': 'Calculate Fixed Deposit returns and maturity amount online free. Plan your FD investments.',
  'ppf-calculator': 'Calculate Public Provident Fund (PPF) returns online free. Plan your PPF investments.',
  'gst-calculator': 'Calculate GST amounts and exclusive/inclusive prices online free. Get accurate GST calculations.',
  'tax-calculator': 'Calculate income tax, GST, and compliance requirements online free.',
  'retirement-calculator': 'Plan your retirement corpus with inflation-adjusted projections online free.',
  'investment-return-calculator': 'Calculate investment returns with compound growth projections online free.',
  'inflation-calculator': 'Calculate how inflation erodes your money\'s value over time online free.',
  'budget-calculator': 'Plan your monthly budget, track expenses, and manage cash flow effectively online free.',
  'currency-converter': 'Convert currencies using real-time exchange rates online free.',
  'loan-amortization-suite': 'Calculate loan amortization schedules online free. Plan your loan payments.',
  'cashflow-budget-architect': 'Plan your monthly budget, track expenses, and manage cash flow effectively.',
  'savings-retirement-hub': 'Plan your savings and retirement online free. Calculate how much you need to save.',
  'wealth-inflation-matrix': 'Calculate how inflation erodes your money\'s value over time online free.',
  'taxation-compliance-deck': 'Calculate income tax, GST, and compliance requirements online free.',
  
  // Health Tools
  'bmi-calculator': 'Calculate your Body Mass Index (BMI) online free. Get health category assessment.',
  'bmr-calculator': 'Calculate your Basal Metabolic Rate (BMR) online free. Understand your daily calorie needs.',
  'tdee-calculator': 'Calculate your Total Daily Energy Expenditure (TDEE) online free.',
  'body-fat-calculator': 'Estimate your body fat percentage online free. Track fitness progress.',
  'ideal-weight-calculator': 'Calculate your ideal body weight based on height and age online free.',
  'healthy-weight-calculator': 'Calculate your healthy weight range based on height and age online free.',
  'calorie-calculator': 'Calculate daily calorie needs for weight management online free.',
  'calories-burned-calculator': 'Estimate calories burned during exercise and daily activities online free.',
  'running-calories-calculator': 'Calculate calories burned while running online free.',
  'walking-calories-calculator': 'Calculate calories burned while walking online free.',
  'heart-rate-calculator': 'Calculate your target heart rate zones for exercise online free.',
  'target-heart-rate-calculator': 'Calculate target heart rate zones for optimal fitness online free.',
  'waist-to-height-ratio-calculator': 'Calculate your waist-to-height ratio instantly online free.',
  'waist-to-hip-ratio-calculator': 'Calculate your waist-to-hip ratio accurately online free.',
  'lean-body-mass-calculator': 'Calculate your lean body mass and muscle content online free.',
  
  // Developer Tools
  'qr-code-studio': 'Create custom QR codes from any URL or text online free. Design branded QR codes.',
  'jwt-base64-deck': 'Decode JWT tokens instantly in your browser online free. Parse JSON Web Tokens.',
  'universal-json-studio': 'View, edit, and format JSON data online free. Parse and validate JSON.',
  'base64-encoder': 'Encode text or files to Base64 format online free. Decode Base64 strings.',
  'code-minifier-beautifier': 'Minify or beautify JavaScript, CSS, and HTML code online free.',
  'markup-formatter': 'Format HTML and markup code for readability online free.',
  'web-crypto-studio': 'Encrypt, decrypt, hash, and sign data using Web Crypto API online free.',
  'webmaster-seo-builder': 'Build SEO-friendly websites and content online free.',
  'developer-utilities': 'Access developer utilities online free. Tools for developers.',
  
  // Construction Tools
  'concrete-calculator': 'Calculate concrete volume needed for slabs, footings, and columns online free.',
  'cement-calculator': 'Calculate exact cement bags needed for your concrete work online free.',
  'brick-calculator': 'Calculate the number of bricks needed for your construction project online free.',
  'steel-weight-calculator': 'Calculate weight of steel bars, beams, and structural steel online free.',
  'rebar-calculator': 'Calculate rebar quantity and weight for reinforced concrete structures online free.',
  'construction-cost-calculator': 'Calculate total construction costs including materials, labor, overhead online free.',
  'house-construction-cost-calculator': 'Estimate house building costs per square foot online free.',
  'sand-calculator': 'Calculate sand volume and weight for construction projects online free.',
};
