import { NextRequest, NextResponse } from 'next/server';
import { lookup } from 'node:dns/promises';
import { isIP } from 'node:net';

export const runtime = 'nodejs';
const MAX_BYTES = 1_500_000;
function privateIp(ip:string){if(isIP(ip)===4){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168);}const s=ip.toLowerCase();return s==='::1'||s==='::'||s.startsWith('fc')||s.startsWith('fd')||s.startsWith('fe80:');}
async function safeUrl(raw:string){let u:URL;try{u=new URL(/^https?:\/\//i.test(raw)?raw:'https://'+raw);}catch{throw new Error('Enter a valid website URL.');}if(!['http:','https:'].includes(u.protocol))throw new Error('Only HTTP and HTTPS URLs are supported.');if(u.username||u.password||u.port)throw new Error('Credentials and custom ports are not supported.');if(['localhost','localhost.localdomain'].includes(u.hostname.toLowerCase()))throw new Error('Local addresses are not supported.');const addresses=await lookup(u.hostname,{all:true,verbatim:true});if(!addresses.length||addresses.some(a=>privateIp(a.address)))throw new Error('Private or local network addresses are not supported.');return u;}
async function fetchLimited(url:URL, redirects=0):Promise<Response>{if(redirects>4)throw new Error('Too many redirects.');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);try{const res=await fetch(url,{redirect:'manual',signal:controller.signal,headers:{'user-agent':'Navorika Website Worth Calculator/1.0'}});if(res.status>=300&&res.status<400){const loc=res.headers.get('location');if(!loc)return res;const next=await safeUrl(new URL(loc,url).toString());return fetchLimited(next,redirects+1);}return res;}finally{clearTimeout(timer);}}
function count(re:RegExp,s:string){return (s.match(re)||[]).length;}
export async function POST(req:NextRequest){try{const body=await req.json();const url=await safeUrl(String(body.url||''));const start=Date.now();const res=await fetchLimited(url);const responseMs=Date.now()-start;const type=res.headers.get('content-type')||'';if(!type.includes('text/html'))return NextResponse.json({error:'The URL did not return an HTML webpage.'},{status:400});const len=Number(res.headers.get('content-length')||0);if(len>MAX_BYTES)return NextResponse.json({error:'The webpage is too large to analyze safely.'},{status:400});const html=(await res.text()).slice(0,MAX_BYTES);const finalUrl=new URL(res.url||url.toString());const plain=html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();const title=(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'').replace(/\s+/g,' ').trim().slice(0,200);const description=(html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)/i)?.[1]||html.match(/<meta[^>]+content=["']([^"']*)["'][^>]+name=["']description["']/i)?.[1]||'').trim().slice(0,300);const links=[...html.matchAll(/<a\b[^>]*href=["']([^"']+)["']/gi)].map(m=>m[1]);let internalLinks=0,externalLinks=0;for(const href of links){try{const x=new URL(href,finalUrl);if(x.hostname===finalUrl.hostname)internalLinks++;else if(['http:','https:'].includes(x.protocol))externalLinks++;}catch{}}
let hasRobots=false,hasSitemap=false;try{const rr=await fetchLimited(await safeUrl(new URL('/robots.txt',finalUrl).toString()));hasRobots=rr.ok;if(rr.ok){const rt=(await rr.text()).slice(0,100000);hasSitemap=/^sitemap:\s*https?:\/\//im.test(rt);}}catch{}if(!hasSitemap){try{const sr=await fetchLimited(await safeUrl(new URL('/sitemap.xml',finalUrl).toString()));hasSitemap=sr.ok;}catch{}}
const flags={https:finalUrl.protocol==='https:',hasCanonical:/<link[^>]+rel=["'][^"']*canonical/i.test(html),hasViewport:/<meta[^>]+name=["']viewport["']/i.test(html),hasStructuredData:/<script[^>]+type=["']application\/ld\+json["']/i.test(html)};const wordCount=plain?plain.split(/\s+/).length:0;const headings=count(/<h[1-6]\b/gi,html);let score=0;score+=flags.https?15:0;score+=flags.hasViewport?10:0;score+=flags.hasCanonical?10:0;score+=flags.hasStructuredData?10:0;score+=hasRobots?10:0;score+=hasSitemap?10:0;score+=title?10:0;score+=description?10:0;score+=wordCount>=300?10:Math.round(wordCount/30);score+=headings>=2?5:headings*2;score=Math.min(100,score);return NextResponse.json({url:finalUrl.toString(),title,description,status:res.status,responseMs,https:flags.https,wordCount,headings,internalLinks,externalLinks,hasCanonical:flags.hasCanonical,hasViewport:flags.hasViewport,hasStructuredData:flags.hasStructuredData,hasRobots,hasSitemap,technicalScore:score});}catch(e){const msg=e instanceof Error?(e.name==='AbortError'?'The website took too long to respond.':e.message):'Could not analyze this website.';return NextResponse.json({error:msg},{status:400});}}
