'use client';

import { useState } from 'react';
import { FileOutput } from 'lucide-react';
import FileDropzone from './FileDropzone';
import { ErrorNotice, PrivacyNotice, ResultActions } from './shared';
import { assertDocxFile } from '@/lib/converters/xml-word/security';
import type { ConversionResult, WordToXmlMode } from '@/lib/converters/xml-word/types';

export default function WordToXmlTool() {
  const [file, setFile] = useState<File | null>(null); const [mode, setMode] = useState<WordToXmlMode>('structured'); const [result, setResult] = useState<(ConversionResult & { text: string }) | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const chooseFile = (next: File) => { setError(''); setResult(null); try { assertDocxFile(next); setFile(next); } catch (cause) { setFile(null); setError(cause instanceof Error ? cause.message : 'Unable to use this file.'); } };
  const convert = async () => { if (!file) return; setBusy(true); setError(''); setResult(null); try { const { convertDocxToXml } = await import('@/lib/converters/xml-word/docx-to-xml'); setResult(await convertDocxToXml(file, mode)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Conversion failed.'); } finally { setBusy(false); } };
  const reset = () => { setFile(null); setResult(null); setError(''); setMode('structured'); };
  return <section className="mx-auto max-w-5xl space-y-5 rounded-3xl border border-slate-200 bg-white p-4 shadow-xl dark:border-slate-800 dark:bg-slate-900 sm:p-6"><PrivacyNotice /><FileDropzone accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" label="Drop a DOCX file here" help="DOCX only · legacy .doc is not supported · maximum 10 MB" file={file} onFile={chooseFile} /><fieldset><legend className="mb-2 font-bold">XML output mode</legend><div className="grid gap-2 sm:grid-cols-2"><label className={`cursor-pointer rounded-xl border p-3 text-sm ${mode === 'structured' ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-950/40' : 'border-slate-300 dark:border-slate-700'}`}><input type="radio" name="word-mode" checked={mode === 'structured'} onChange={() => setMode('structured')} className="mr-2" /><span className="font-bold">Clean structured XML</span><span className="mt-1 block text-[var(--muted-foreground)]">Headings, paragraphs, lists, tables, and basic hyperlinks.</span></label><label className={`cursor-pointer rounded-xl border p-3 text-sm ${mode === 'raw' ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-950/40' : 'border-slate-300 dark:border-slate-700'}`}><input type="radio" name="word-mode" checked={mode === 'raw'} onChange={() => setMode('raw')} className="mr-2" /><span className="font-bold">Raw WordprocessingML</span><span className="mt-1 block text-[var(--muted-foreground)]">Extract the original word/document.xml part.</span></label></div></fieldset>{error && <ErrorNotice message={error} />}{result && <div><label htmlFor="xml-preview" className="mb-2 block font-bold">XML preview</label><textarea id="xml-preview" readOnly value={result.text} className="min-h-56 w-full max-w-full rounded-xl border border-slate-300 bg-slate-50 p-3 font-mono text-xs dark:border-slate-700 dark:bg-slate-950" /></div>}{result ? <ResultActions {...result} onReset={reset} /> : <button type="button" onClick={convert} disabled={busy || !file} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50"><FileOutput className="size-5" /> {busy ? 'Extracting XML…' : 'Convert DOCX to XML'}</button>}</section>;
}
