'use client';

import { useState } from 'react';
import { FileOutput } from 'lucide-react';
import FileDropzone from './FileDropzone';
import { ErrorNotice, PrivacyNotice, ResultActions } from './shared';
import { assertXmlFile } from '@/lib/converters/xml-word/security';
import type { ConversionResult, XmlToWordMode } from '@/lib/converters/xml-word/types';

const sample = `<?xml version="1.0" encoding="UTF-8"?>\n<catalog>\n  <book id="bk-101"><title>XML Handbook</title><price currency="USD">24.00</price></book>\n  <book id="bk-102"><title>Document Workflows</title><price currency="USD">29.00</price></book>\n</catalog>`;

export default function XmlToWordTool() {
  const [source, setSource] = useState(''); const [file, setFile] = useState<File | null>(null); const [mode, setMode] = useState<XmlToWordMode>('hierarchy'); const [result, setResult] = useState<ConversionResult | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const chooseFile = async (next: File) => { setError(''); setResult(null); try { assertXmlFile(next); const text = await next.text(); setFile(next); setSource(text); } catch (cause) { setFile(null); setError(cause instanceof Error ? cause.message : 'Unable to read the XML file.'); } };
  const convert = async () => { setBusy(true); setError(''); setResult(null); try { const { convertXmlToDocx } = await import('@/lib/converters/xml-word/xml-to-docx'); setResult(await convertXmlToDocx(source, mode, file?.name)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Conversion failed.'); } finally { setBusy(false); } };
  const reset = () => { setSource(''); setFile(null); setResult(null); setError(''); setMode('hierarchy'); };
  return <section className="mx-auto max-w-5xl space-y-5 rounded-3xl border border-slate-200 bg-white p-4 shadow-xl dark:border-slate-800 dark:bg-slate-900 sm:p-6"><PrivacyNotice /><FileDropzone accept=".xml,application/xml,text/xml" label="Drop an XML file here" help="XML only · maximum 10 MB · or paste XML below" file={file} onFile={chooseFile} /><div><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><label htmlFor="xml-source" className="font-bold">XML input</label><button type="button" onClick={() => { setSource(sample); setFile(null); setResult(null); setError(''); }} className="text-sm font-bold text-indigo-600 hover:underline">Load example</button></div><textarea id="xml-source" value={source} onChange={(event) => { setSource(event.target.value); setFile(null); setResult(null); setError(''); }} spellCheck={false} placeholder="Paste XML here…" className="min-h-64 w-full max-w-full rounded-xl border border-slate-300 bg-slate-50 p-3 font-mono text-sm outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 dark:border-slate-700 dark:bg-slate-950" /></div><fieldset><legend className="mb-2 font-bold">Word layout mode</legend><div className="grid gap-2 sm:grid-cols-3">{([['hierarchy','Readable hierarchy'],['table','Table / data'],['raw','Formatted XML code']] as const).map(([value,label]) => <label key={value} className={`cursor-pointer rounded-xl border p-3 text-sm ${mode === value ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-950/40' : 'border-slate-300 dark:border-slate-700'}`}><input type="radio" name="xml-mode" value={value} checked={mode === value} onChange={() => setMode(value)} className="mr-2" /> <span className="font-bold">{label}</span></label>)}</div></fieldset>{error && <ErrorNotice message={error} />}{result ? <ResultActions {...result} onReset={reset} /> : <button type="button" onClick={convert} disabled={busy || !source.trim()} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50"><FileOutput className="size-5" /> {busy ? 'Creating DOCX…' : 'Convert XML to DOCX'}</button>}</section>;
}
