'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Download, LayoutGrid, ShieldCheck, Upload, X } from 'lucide-react';
type Item={file:File;url:string};
export default function Page(){const[items,setItems]=useState<Item[]>([]);const[columns,setColumns]=useState(3);const[gap,setGap]=useState(12);const[error,setError]=useState('');const input=useRef<HTMLInputElement>(null);const itemsRef=useRef<Item[]>([]);useEffect(()=>{itemsRef.current=items},[items]);useEffect(()=>()=>itemsRef.current.forEach(i=>URL.revokeObjectURL(i.url)),[]);
  const add=(list:FileList|null)=>{if(!list)return;const files=Array.from(list).filter(f=>['image/jpeg','image/png','image/webp'].includes(f.type));if(files.length!==list.length){setError('Only JPG, PNG, and WebP images are accepted.');return;}setItems(current=>[...current,...files.map(file=>({file,url:URL.createObjectURL(file)}))].slice(0,12));setError('');};
  const create=async()=>{if(!items.length)return;try{const bitmaps=await Promise.all(items.map(i=>createImageBitmap(i.file)));const size=1200;const rows=Math.ceil(bitmaps.length/columns);const cellW=(size-gap*(columns+1))/columns;const cellH=cellW;const canvas=document.createElement('canvas');canvas.width=size;canvas.height=Math.ceil(cellH*rows+gap*(rows+1));const ctx=canvas.getContext('2d');if(!ctx)throw new Error();ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);bitmaps.forEach((img,index)=>{const col=index%columns,row=Math.floor(index/columns),x=gap+col*(cellW+gap),y=gap+row*(cellH+gap),scale=Math.max(cellW/img.width,cellH/img.height),w=img.width*scale,h=img.height*scale;ctx.save();ctx.beginPath();ctx.rect(x,y,cellW,cellH);ctx.clip();ctx.drawImage(img,x+(cellW-w)/2,y+(cellH-h)/2,w,h);ctx.restore();img.close();});const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/png'));if(!blob)throw new Error();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='photo-collage.png';a.click();URL.revokeObjectURL(url);}catch{setError('The collage could not be created. Try fewer or smaller images.');}};
  return <main className="max-w-5xl mx-auto px-6 py-12"><Link href="/categories/image-tools" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 mb-8"><ArrowLeft className="h-4 w-4"/> Back to Image Tools</Link><div className="text-center mb-8"><div className="inline-flex gap-2 text-xs font-bold text-emerald-600"><ShieldCheck className="h-4 w-4"/> LOCAL PROCESSING</div><h1 className="text-4xl font-black mt-4">Photo Collage Maker</h1><p className="mt-3 text-slate-500">Create a square-cell PNG collage from up to 12 images.</p></div><section className="bg-white dark:bg-slate-900 rounded-3xl border shadow-xl p-8"><button onClick={()=>input.current?.click()} className="w-full p-8 border-2 border-dashed rounded-2xl flex flex-col items-center"><Upload className="h-8 w-8 text-indigo-500"/><span className="mt-2 font-bold">Choose JPG, PNG, or WebP images</span></button><input ref={input} type="file" multiple accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>add(e.target.files)}/>{items.length>0&&<><div className="mt-5 grid grid-cols-3 sm:grid-cols-4 gap-3">{items.map((item,index)=><div key={`${item.file.name}-${index}`} className="relative aspect-square"><img src={item.url} alt={`Collage source ${index+1}`} className="w-full h-full object-cover rounded-xl"/><button onClick={()=>setItems(current=>current.filter((_,i)=>i!==index))} aria-label={`Remove image ${index+1}`} className="absolute top-1 right-1 p-1 bg-black/70 text-white rounded-full"><X className="h-4 w-4"/></button></div>)}</div><div className="mt-5 grid sm:grid-cols-2 gap-4"><label className="font-bold text-sm">Columns<select value={columns} onChange={e=>setColumns(Number(e.target.value))} className="mt-2 w-full p-3 rounded-xl border bg-slate-50 dark:bg-slate-800"><option value={2}>2</option><option value={3}>3</option><option value={4}>4</option></select></label><label className="font-bold text-sm">Gap: {gap}px<input type="range" min={0} max={40} value={gap} onChange={e=>setGap(Number(e.target.value))} className="mt-4 w-full"/></label></div><button onClick={()=>void create()} className="mt-5 w-full py-4 rounded-xl bg-indigo-600 text-white font-bold flex justify-center gap-2"><Download className="h-5 w-5"/> Create PNG Collage</button></>}{error&&<p className="mt-4 text-red-600">{error}</p>}</section></main>}
