'use client';
import { useMemo,useState } from 'react';
import {deckBoards,drywall,fence,landscapeVolume,pavers,polymericSand,postHoleConcrete,roofPitch,stairs} from '@/lib/calculations/constructionExpansion';

const inputClass='mt-2 w-full rounded-xl border border-[var(--border)] bg-[var(--background)] px-3 py-2';
function Field({label,value,onChange,step='0.1',min='0'}:{label:string;value:number;onChange:(value:number)=>void;step?:string;min?:string}){return <label className="text-sm font-semibold">{label}<input aria-label={label} type="number" value={value} min={min} step={step} onChange={e=>onChange(Number(e.target.value))} className={inputClass}/></label>}
function Card({children}:{children:React.ReactNode}){return <section className="rounded-3xl border border-[var(--border)] bg-[var(--card)] p-5 sm:p-7">{children}</section>}
function Results({values,error}:{values:Array<[string,string|number]>;error?:string}){return <Card><h2 className="text-xl font-bold">Planning result</h2>{error?<p role="alert" className="mt-4 text-red-600">{error}</p>:<dl className="mt-4 grid gap-3 sm:grid-cols-2">{values.map(([label,value])=><div key={label} className="rounded-xl bg-[var(--background)] p-4"><dt className="text-xs text-[var(--muted-foreground)]">{label}</dt><dd className="mt-1 text-xl font-black">{value}</dd></div>)}</dl>}</Card>}
function calculate<T>(fn:()=>T){try{return{data:fn(),error:''}}catch(error){return{data:null,error:error instanceof Error?error.message:'Check the entered values.'}}}
const fixed=(value:number,digits=2)=>Number.isFinite(value)?value.toFixed(digits):'—';

export function RoofPitchCalculator(){const[rise,setRise]=useState(6);const[run,setRun]=useState(12);const[span,setSpan]=useState(12);const result=useMemo(()=>calculate(()=>roofPitch(rise,run,span)),[rise,run,span]);const r=result.data;return <div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-bold">Roof slope dimensions</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Rise" value={rise} onChange={setRise}/><Field label="Run" value={run} onChange={setRun}/><Field label="Optional horizontal rafter run (ft)" value={span} onChange={setSpan}/></div><p className="mt-4 text-sm">Use the same unit for rise and run. Results describe geometry only, not structural adequacy.</p></Card><Results error={result.error} values={r?[['Pitch',`${fixed(r.pitch12)}:12`],['Angle',`${fixed(r.angle,3)}°`],['Slope',`${fixed(r.percent)}%`],['Rafter multiplier',fixed(r.multiplier,4)],['Rafter length',`${fixed(r.rafterLength??0)} ft`]]:[]}/></div>}

export function StairStringerCalculator(){const[rise,setRise]=useState(108);const[max,setMax]=useState(7.75);const[tread,setTread]=useState(10);const[width,setWidth]=useState(36);const result=useMemo(()=>calculate(()=>stairs(rise,max,tread,width)),[rise,max,tread,width]);const r=result.data;return <div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-bold">Stair dimensions (inches)</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Total rise" value={rise} onChange={setRise}/><Field label="Desired / maximum riser" value={max} onChange={setMax}/><Field label="Tread depth" value={tread} onChange={setTread}/><Field label="Optional stair width" value={width} onChange={setWidth}/></div><p className="mt-4 text-sm">Planning geometry only. Codes, landings, headroom and stringer design vary.</p></Card><Results error={result.error} values={r?[['Riser count',r.risers],['Actual riser',`${fixed(r.actualRiser)} in`],['Tread count',r.treads],['Total run',`${fixed(r.totalRun)} in`],['Stringer length',`${fixed(r.stringerLength)} in`],['Angle',`${fixed(r.angle)}°`]]:[]}/></div>}

export function DeckBoardCalculator(){const[length,setLength]=useState(20);const[width,setWidth]=useState(12);const[boardWidth,setBoardWidth]=useState(5.5);const[boardLength,setBoardLength]=useState(12);const[gap,setGap]=useState(.25);const[waste,setWaste]=useState(10);const[orientation,setOrientation]=useState<'length'|'width'>('length');const result=useMemo(()=>calculate(()=>deckBoards(length,width,boardWidth,boardLength,gap,orientation,waste)),[length,width,boardWidth,boardLength,gap,orientation,waste]);const r=result.data;return <div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-bold">Deck and actual board dimensions</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Deck length (ft)" value={length} onChange={setLength}/><Field label="Deck width (ft)" value={width} onChange={setWidth}/><Field label="Actual board width (in)" value={boardWidth} onChange={setBoardWidth}/><Field label="Stock board length (ft)" value={boardLength} onChange={setBoardLength}/><Field label="Gap (in)" value={gap} onChange={setGap}/><Field label="Waste (%)" value={waste} onChange={setWaste}/><label className="text-sm font-semibold">Boards run along<select value={orientation} onChange={e=>setOrientation(e.target.value as 'length'|'width')} className={inputClass}><option value="length">Deck length</option><option value="width">Deck width</option></select></label></div><p className="mt-4 text-sm">Enter actual board width, not nominal lumber size. Rows account for the gap between boards.</p></Card><Results error={result.error} values={r?[['Board rows',r.rows],['Pieces per row',r.piecesPerRow],['Boards before waste',r.base],['Boards to buy',r.required],['Linear feet',fixed(r.linearFeet)],['Board-face coverage',`${fixed(r.coverage)} ft²`],['Waste allowance',`${r.wasteBoards} boards`]]:[]}/></div>}

export function FenceCalculator(){const[length,setLength]=useState(150);const[section,setSection]=useState(8);const[corners,setCorners]=useState(2);const[gates,setGates]=useState(1);const[gateWidth,setGateWidth]=useState(4);const[waste,setWaste]=useState(5);const[rails,setRails]=useState(2);const[mode,setMode]=useState<'panel'|'spacing'>('panel');const result=useMemo(()=>calculate(()=>fence(length,mode,section,corners,gates,gateWidth,waste,rails)),[length,mode,section,corners,gates,gateWidth,waste,rails]);const r=result.data;return <div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-bold">Fence layout</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Total fence length (ft)" value={length} onChange={setLength}/><label className="text-sm font-semibold">Layout mode<select value={mode} onChange={e=>setMode(e.target.value as 'panel'|'spacing')} className={inputClass}><option value="panel">Panel length</option><option value="spacing">Post spacing</option></select></label><Field label={mode==='panel'?'Panel length (ft)':'Maximum post spacing (ft)'} value={section} onChange={setSection}/><Field label="Corners" value={corners} onChange={setCorners} step="1"/><Field label="Gates" value={gates} onChange={setGates} step="1"/><Field label="Width per gate (ft)" value={gateWidth} onChange={setGateWidth}/><Field label="Waste (%)" value={waste} onChange={setWaste}/><Field label="Rails per section" value={rails} onChange={setRails} step="1"/></div></Card><Results error={result.error} values={r?[['Net fenced length',`${fixed(r.net)} ft`],['Sections',r.sections],['Panels incl. waste',r.panels||'N/A'],['Total posts',r.posts],['Line posts',r.linePosts],['Corner/end/gate posts',r.cornerEnd],['Rails',r.rails]]:[]}/></div>}

export function PostHoleConcreteCalculator(){const[diameter,setDiameter]=useState(12);const[depth,setDepth]=useState(36);const[count,setCount]=useState(8);const[shape,setShape]=useState<'round'|'rectangle'>('round');const[postA,setPostA]=useState(4);const[postB,setPostB]=useState(4);const[yieldFt,setYieldFt]=useState(.6);const result=useMemo(()=>calculate(()=>postHoleConcrete(diameter,depth,count,shape,postA,postB,yieldFt)),[diameter,depth,count,shape,postA,postB,yieldFt]);const r=result.data;return <div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-bold">Hole and post dimensions</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Hole diameter (in)" value={diameter} onChange={setDiameter}/><Field label="Hole depth (in)" value={depth} onChange={setDepth}/><Field label="Hole count" value={count} onChange={setCount} step="1"/><label className="text-sm font-semibold">Post shape<select value={shape} onChange={e=>setShape(e.target.value as 'round'|'rectangle')} className={inputClass}><option value="round">Round</option><option value="rectangle">Square / rectangular</option></select></label><Field label={shape==='round'?'Post diameter (in)':'Post width (in)'} value={postA} onChange={setPostA}/>{shape==='rectangle'&&<Field label="Post thickness (in)" value={postB} onChange={setPostB}/>}<Field label="Concrete yield per bag (ft³)" value={yieldFt} onChange={setYieldFt}/></div></Card><Results error={result.error} values={r?[['Concrete per hole',`${fixed(r.perHole,3)} ft³`],['Post displacement',`${fixed(r.displacement,3)} ft³`],['Total concrete',`${fixed(r.ft3)} ft³`],['Cubic yards',fixed(r.yd3,3)],['Bags',r.bags]]:[]}/></div>}

export function DrywallCalculator(){const[mode,setMode]=useState<'dimensions'|'area'>('dimensions');const[length,setLength]=useState(40);const[height,setHeight]=useState(8);const[area,setArea]=useState(320);const[ceiling,setCeiling]=useState(0);const[openings,setOpenings]=useState(40);const[sheetW,setSheetW]=useState(4);const[sheetH,setSheetH]=useState(8);const[waste,setWaste]=useState(10);const wall=mode==='dimensions'?length*height:area;const result=useMemo(()=>calculate(()=>drywall(wall,ceiling,openings,sheetW,sheetH,waste)),[wall,ceiling,openings,sheetW,sheetH,waste]);const r=result.data;return <div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-bold">Drywall area and sheet size</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Wall input<select value={mode} onChange={e=>setMode(e.target.value as 'dimensions'|'area')} className={inputClass}><option value="dimensions">Length × height</option><option value="area">Known area</option></select></label>{mode==='dimensions'?<><Field label="Combined wall length (ft)" value={length} onChange={setLength}/><Field label="Wall height (ft)" value={height} onChange={setHeight}/></>:<Field label="Wall area (ft²)" value={area} onChange={setArea}/>}<Field label="Optional ceiling area (ft²)" value={ceiling} onChange={setCeiling}/><Field label="Openings (ft²)" value={openings} onChange={setOpenings}/><Field label="Sheet width (ft)" value={sheetW} onChange={setSheetW}/><Field label="Sheet length (ft)" value={sheetH} onChange={setSheetH}/><Field label="Waste (%)" value={waste} onChange={setWaste}/></div></Card><Results error={result.error} values={r?[['Net area',`${fixed(r.net)} ft²`],['Waste-adjusted area',`${fixed(r.adjusted)} ft²`],['Base sheets',r.base],['Sheets to buy',r.sheets],['Waste sheets',r.wasteSheets],['Approx. screws',r.screws],['Approx. tape',`${r.tapeFt} ft`],['Approx. compound',`${r.compoundGallons} gal`]]:[]}/></div>}

function AreaFields({mode,setMode,length,setLength,width,setWidth,area,setArea}:{mode:'dimensions'|'area';setMode:(v:'dimensions'|'area')=>void;length:number;setLength:(v:number)=>void;width:number;setWidth:(v:number)=>void;area:number;setArea:(v:number)=>void}){return <><label className="text-sm font-semibold">Project input<select value={mode} onChange={e=>setMode(e.target.value as 'dimensions'|'area')} className={inputClass}><option value="dimensions">Length × width</option><option value="area">Known area</option></select></label>{mode==='dimensions'?<><Field label="Length (ft)" value={length} onChange={setLength}/><Field label="Width (ft)" value={width} onChange={setWidth}/></>:<Field label="Area (ft²)" value={area} onChange={setArea}/>}</>}
function useArea(){const[mode,setMode]=useState<'dimensions'|'area'>('dimensions');const[length,setLength]=useState(10);const[width,setWidth]=useState(10);const[area,setArea]=useState(100);return{mode,setMode,length,setLength,width,setWidth,area,setArea,value:mode==='dimensions'?length*width:area}}

export function PaverCalculator(){const a=useArea();const[paverL,setPaverL]=useState(8);const[paverW,setPaverW]=useState(4);const[waste,setWaste]=useState(10);const[pallet,setPallet]=useState(480);const result=useMemo(()=>calculate(()=>pavers(a.value,paverL,paverW,waste,pallet)),[a.value,paverL,paverW,waste,pallet]);const r=result.data;return <div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-bold">Project and paver dimensions</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><AreaFields {...a}/><Field label="Paver length (in)" value={paverL} onChange={setPaverL}/><Field label="Paver width (in)" value={paverW} onChange={setPaverW}/><Field label="Waste (%)" value={waste} onChange={setWaste}/><Field label="Optional pavers per pallet" value={pallet} onChange={setPallet} step="1"/></div></Card><Results error={result.error} values={r?[['Net area',`${fixed(r.areaFt2)} ft²`],['Area per paver',`${fixed(r.each,4)} ft²`],['Base pavers',r.base],['Pavers incl. waste',r.count],['Waste pavers',r.wastePavers],['Pallets',r.pallets??'N/A']]:[]}/></div>}

export function PolymericSandCalculator(){const a=useArea();const[paverL,setPaverL]=useState(8);const[paverW,setPaverW]=useState(4);const[jointW,setJointW]=useState(.25);const[depth,setDepth]=useState(1.5);const[density,setDensity]=useState(100);const[bag,setBag]=useState(40);const[waste,setWaste]=useState(10);const result=useMemo(()=>calculate(()=>polymericSand(a.value,paverL,paverW,jointW,depth,density,bag,waste)),[a.value,paverL,paverW,jointW,depth,density,bag,waste]);const r=result.data;return <div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-bold">Paver joint assumptions</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><AreaFields {...a}/><Field label="Paver length (in)" value={paverL} onChange={setPaverL}/><Field label="Paver width (in)" value={paverW} onChange={setPaverW}/><Field label="Joint width (in)" value={jointW} onChange={setJointW}/><Field label="Joint depth (in)" value={depth} onChange={setDepth}/><Field label="Bulk density (lb/ft³)" value={density} onChange={setDensity}/><Field label="Bag size (lb)" value={bag} onChange={setBag}/><Field label="Waste (%)" value={waste} onChange={setWaste}/></div><p className="mt-4 text-sm">Coverage varies by paver geometry, compaction and manufacturer. Override density with product information when available.</p></Card><Results error={result.error} values={r?[['Joint volume',`${fixed(r.volumeFt3,3)} ft³`],['Sand weight incl. waste',`${fixed(r.weight)} lb`],['Bags',r.bags]]:[]}/></div>}

export function MulchCalculator(){const a=useArea();const[shape,setShape]=useState<'rectangle'|'circle'>('rectangle');const[depth,setDepth]=useState(3);const[bag,setBag]=useState(2);const projectArea=shape==='circle'&&a.mode==='dimensions'?Math.PI*(a.length/2)**2:a.value;const result=useMemo(()=>calculate(()=>landscapeVolume(projectArea,depth)),[projectArea,depth]);const r=result.data;return <div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-bold">Mulch bed</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Shape<select value={shape} onChange={e=>setShape(e.target.value as 'rectangle'|'circle')} className={inputClass}><option value="rectangle">Rectangle / known area</option><option value="circle">Circle (length is diameter)</option></select></label><AreaFields {...a}/><Field label="Depth (in)" value={depth} onChange={setDepth}/><Field label="Bag volume (ft³)" value={bag} onChange={setBag}/></div></Card><Results error={result.error} values={r?[['Area',`${fixed(projectArea)} ft²`],['Volume',`${fixed(r.ft3)} ft³`],['Cubic yards',fixed(r.yd3,3)],['Liters',fixed(r.liters)],['Bags',Math.ceil(r.ft3/bag)]]:[]}/></div>}

export function TopsoilCalculator(){const a=useArea();const[depth,setDepth]=useState(3);const[density,setDensity]=useState(75);const result=useMemo(()=>calculate(()=>landscapeVolume(a.value,depth)),[a.value,depth]);const r=result.data;return <div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-bold">Topsoil coverage</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><AreaFields {...a}/><Field label="Depth (in)" value={depth} onChange={setDepth}/><Field label="Editable density (lb/ft³)" value={density} onChange={setDensity}/></div><p className="mt-4 text-sm">Weight varies materially with moisture, compaction and soil composition.</p></Card><Results error={result.error} values={r?[['Volume',`${fixed(r.ft3)} ft³`],['Cubic yards',fixed(r.yd3,3)],['Cubic meters',fixed(r.m3,3)],['Estimated US tons',fixed(r.ft3*density/2000,2)]]:[]}/></div>}
