'use client';

import { ArrowDownUp, Copy, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';

export default function UrlEncoderDecoder() {
  const [input, setInput] = useState('hello world?tag=one&tag=two'); const [mode, setMode] = useState<'encode'|'decode'>('encode'); const [component, setComponent] = useState(true);
  const result = useMemo(() => { try { return { output: mode === 'encode' ? (component ? encodeURIComponent(input) : encodeURI(input)) : (component ? decodeURIComponent(input) : decodeURI(input)), error: '' }; } catch { return { output: '', error: 'The encoded text is malformed. Check incomplete percent escapes such as %E0.' }; } }, [input, mode, component]);
  return <section className="rounded-3xl border border-[var(--border)] bg-[var(--card)] p-5 sm:p-7"><div className="flex flex-wrap gap-3"><label className="text-sm font-semibold">Operation<select value={mode} onChange={(event) => setMode(event.target.value as 'encode'|'decode')} className="ml-2 rounded-xl border border-[var(--border)] bg-[var(--background)] px-3 py-2"><option value="encode">Encode</option><option value="decode">Decode</option></select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={component} onChange={(event) => setComponent(event.target.checked)} /> Component mode (preserve no URL separators)</label></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><label className="font-bold">Input<textarea value={input} onChange={(event) => setInput(event.target.value)} className="mt-2 min-h-64 w-full rounded-2xl border border-[var(--border)] bg-[var(--background)] p-4 font-mono text-sm font-normal" /></label><label className="font-bold">Output<textarea value={result.output} readOnly className="mt-2 min-h-64 w-full rounded-2xl border border-[var(--border)] bg-[var(--background)] p-4 font-mono text-sm font-normal" /></label></div>{result.error && <p role="alert" className="mt-3 text-sm text-red-600">{result.error}</p>}<div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => { setInput(result.output); setMode(mode === 'encode' ? 'decode' : 'encode'); }} disabled={!!result.error} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-4 py-2 text-sm font-semibold"><ArrowDownUp className="size-4" /> Swap</button><button type="button" onClick={() => void navigator.clipboard.writeText(result.output)} disabled={!result.output} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-4 py-2 text-sm font-semibold"><Copy className="size-4" /> Copy</button><button type="button" onClick={() => setInput('')} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-4 py-2 text-sm font-semibold"><Trash2 className="size-4" /> Clear</button></div></section>;
}
