'use client';

import { useMemo, useState } from 'react';
import { Globe2, Loader2, ShieldCheck, TrendingUp } from 'lucide-react';

type Scan = { url:string; title:string; status:number; responseMs:number; https:boolean; wordCount:number; headings:number; internalLinks:number; externalLinks:number; hasCanonical:boolean; hasViewport:boolean; hasStructuredData:boolean; hasRobots:boolean; hasSitemap:boolean; technicalScore:number };
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);

export default function WebsiteWorthCalculator(){
 const [url,setUrl]=useState(''); const [visits,setVisits]=useState(''); const [revenue,setRevenue]=useState(''); const [profit,setProfit]=useState(''); const [scan,setScan]=useState<Scan|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const valuation=useMemo(()=>{ const v=Math.max(0,Number(visits)||0), r=Math.max(0,Number(revenue)||0), p=Math.max(0,Number(profit)||0); let monthly=p||r*0.65; if(!monthly&&v) monthly=(v/1000)*12*0.65; if(!monthly)return null; const quality=scan?0.85+(scan.technicalScore/100)*0.3:1; return {low:monthly*24*quality,mid:monthly*32*quality,high:monthly*40*quality}; },[visits,revenue,profit,scan]);
 async function analyze(){setLoading(true);setError('');setScan(null);try{const res=await fetch('/api/website-worth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not analyze this website.');setScan(data);}catch(e){setError(e instanceof Error?e.message:'Could not analyze this website.');}finally{setLoading(false);}}
 return <div className="space-y-6">
  <section className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5 shadow-sm sm:p-7"><div className="grid gap-4 lg:grid-cols-[1fr_auto] lg:items-end"><label className="block"><span className="mb-2 block text-sm font-bold">Website URL</span><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com" className="w-full rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 outline-none focus:ring-2 focus:ring-indigo-500" /></label><button onClick={analyze} disabled={loading||!url.trim()} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-indigo-600 px-6 font-bold text-white disabled:opacity-50">{loading?<Loader2 className="size-5 animate-spin"/>:<Globe2 className="size-5"/>}{loading?'Analyzing…':'Analyze Website'}</button></div>{error&&<p className="mt-3 text-sm font-semibold text-red-600">{error}</p>}</section>
  {scan&&<section className="grid gap-4 md:grid-cols-3"><Metric label="Technical score" value={scan.technicalScore+'/100'} note="Observable website signals"/><Metric label="Response" value={scan.responseMs+' ms'} note={'HTTP '+scan.status+' · '+(scan.https?'HTTPS':'HTTP')}/><Metric label="Page content" value={scan.wordCount.toLocaleString()+' words'} note={scan.headings+' headings · '+scan.internalLinks+' internal links'}/></section>}
  {scan&&<section className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5 sm:p-7"><h2 className="text-xl font-black">Website review</h2><p className="mt-2 text-sm text-[var(--muted-foreground)]">{scan.title||new URL(scan.url).hostname}</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Check ok={scan.https} text="HTTPS enabled"/><Check ok={scan.hasViewport} text="Mobile viewport"/><Check ok={scan.hasCanonical} text="Canonical tag"/><Check ok={scan.hasStructuredData} text="Structured data"/><Check ok={scan.hasRobots} text="robots.txt reachable"/><Check ok={scan.hasSitemap} text="Sitemap detected"/></div></section>}
  <section className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5 sm:p-7"><div className="flex items-start gap-3"><TrendingUp className="mt-1 size-6 text-indigo-600"/><div><h2 className="text-xl font-black">Website value estimate</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">For a defensible dollar estimate, add any data you know. Private revenue and analytics cannot be discovered reliably from a public URL.</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><Input label="Monthly visits" value={visits} set={setVisits} placeholder="e.g. 50000"/><Input label="Monthly revenue (USD)" value={revenue} set={setRevenue} placeholder="optional"/><Input label="Monthly profit (USD)" value={profit} set={setProfit} placeholder="optional"/></div>{valuation?<div className="mt-6 rounded-2xl bg-[var(--muted)] p-5"><p className="text-sm font-bold uppercase tracking-wide text-[var(--muted-foreground)]">Estimated market range</p><p className="mt-2 text-3xl font-black sm:text-4xl">{money(valuation.low)} – {money(valuation.high)}</p><p className="mt-2 text-sm text-[var(--muted-foreground)]">Midpoint {money(valuation.mid)}. Model uses approximately 24–40× normalized monthly profit; traffic-only estimates assume $12 RPM and 65% margin. Technical score makes only a modest adjustment.</p></div>:<div className="mt-6 rounded-xl border border-dashed border-[var(--border)] p-4 text-sm text-[var(--muted-foreground)]">Enter monthly visits, revenue, or profit to calculate a value range. Profit is preferred when available.</div>}</section>
  <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-100"><strong>Important:</strong> This is an indicative valuation, not a certified appraisal or an offer to buy. Actual sale value depends on verified analytics, revenue quality, traffic sources, niche, growth, owner workload, concentration risk, assets, liabilities, and buyer demand.</section>
 </div>;
}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5"><p className="text-sm font-semibold text-[var(--muted-foreground)]">{label}</p><p className="mt-1 text-2xl font-black">{value}</p><p className="mt-1 text-xs text-[var(--muted-foreground)]">{note}</p></div>}
function Check({ok,text}:{ok:boolean;text:string}){return <div className="flex items-center gap-2 rounded-xl border border-[var(--border)] p-3"><ShieldCheck className={'size-5 '+(ok?'text-emerald-600':'text-[var(--muted-foreground)]')}/><span className="text-sm font-semibold">{text}: {ok?'Yes':'Not detected'}</span></div>}
function Input({label,value,set,placeholder}:{label:string;value:string;set:(v:string)=>void;placeholder:string}){return <label><span className="mb-2 block text-sm font-bold">{label}</span><input inputMode="decimal" value={value} onChange={e=>set(e.target.value.replace(/[^0-9.]/g,''))} placeholder={placeholder} className="w-full rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 outline-none focus:ring-2 focus:ring-indigo-500"/></label>}
