import { XML_WORD_LIMITS } from './config';
const DOCX_MIMES = new Set(['', 'application/octet-stream', 'application/zip', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']);
const XML_MIMES = new Set(['', 'application/xml', 'text/xml', 'text/plain', 'application/octet-stream']);
export class ConversionError extends Error { constructor(message: string) { super(message); this.name = 'ConversionError'; } }
export function assertUploadSize(size: number) { if (size <= 0) throw new ConversionError('Choose a non-empty file.'); if (size > XML_WORD_LIMITS.maxUploadBytes) throw new ConversionError('The file exceeds the 10 MB upload limit.'); }
export function assertXmlFile(file: Pick<File, 'name' | 'type' | 'size'>) { assertUploadSize(file.size); if (!file.name.toLowerCase().endsWith('.xml')) throw new ConversionError('Choose a file with the .xml extension.'); if (!XML_MIMES.has(file.type.toLowerCase())) throw new ConversionError(`The reported file type (${file.type}) is not an XML type.`); }
export function assertDocxFile(file: Pick<File, 'name' | 'type' | 'size'>) { assertUploadSize(file.size); const lower = file.name.toLowerCase(); if (lower.endsWith('.doc')) throw new ConversionError('Legacy .doc files are not supported. Save the document as .docx in Word and try again.'); if (!lower.endsWith('.docx')) throw new ConversionError('Choose a Word document with the .docx extension.'); if (!DOCX_MIMES.has(file.type.toLowerCase())) throw new ConversionError(`The reported file type (${file.type}) is not a DOCX type.`); }
export function assertSafeXmlSource(source: string) { const bytes = new TextEncoder().encode(source).byteLength; if (!source.trim()) throw new ConversionError('Enter XML or upload a non-empty XML file.'); if (bytes > XML_WORD_LIMITS.maxUploadBytes) throw new ConversionError('The XML exceeds the 10 MB input limit.'); if (/<!\s*(?:DOCTYPE|ENTITY)\b|\b(?:SYSTEM|PUBLIC)\s+["']/i.test(source)) throw new ConversionError('DTD, ENTITY, SYSTEM, and PUBLIC declarations are blocked to prevent external-entity and entity-expansion attacks.'); if (source.includes('\0')) throw new ConversionError('The XML contains unsupported null characters.'); }
export function assertZipMagic(bytes: Uint8Array) { const valid = bytes.length >= 4 && bytes[0] === 0x50 && bytes[1] === 0x4b && ((bytes[2] === 0x03 && bytes[3] === 0x04) || (bytes[2] === 0x05 && bytes[3] === 0x06) || (bytes[2] === 0x07 && bytes[3] === 0x08)); if (!valid) throw new ConversionError('This file is not a valid DOCX ZIP package.'); }
export function safeDownloadName(name: string, extension: string) { const stem = name.replace(/\.[^.]+$/, '').replace(/[^a-z0-9._-]+/gi, '-').replace(/^-+|-+$/g, '') || 'converted'; return `${stem}.${extension}`; }
