import { BorderStyle, Document, HeadingLevel, Packer, Paragraph, ShadingType, Table, TableCell, TableRow, TextRun, WidthType } from 'docx';
import formatXml from 'xml-formatter';
import { parseXml } from './xml-parser';
import { findRepeatedSiblingTable } from './xml-table';
import { safeDownloadName } from './security';
import type { ConversionResult, XmlToWordMode, XmlTreeNode } from './types';
const headings = [HeadingLevel.HEADING_1, HeadingLevel.HEADING_2, HeadingLevel.HEADING_3, HeadingLevel.HEADING_4, HeadingLevel.HEADING_5, HeadingLevel.HEADING_6];
function hierarchyParagraphs(node: XmlTreeNode, depth = 0): Paragraph[] { const paragraphs = [new Paragraph({ text: node.name, heading: headings[Math.min(depth, 5)] })]; const attrs = Object.entries(node.attributes); if (attrs.length) paragraphs.push(new Paragraph({ children: [new TextRun({ text: attrs.map(([key, value]) => `@${key} = ${value}`).join('  •  '), color: '475569', italics: true })] })); if (node.text) paragraphs.push(new Paragraph({ children: [new TextRun(node.text)] })); for (const child of node.children) paragraphs.push(...hierarchyParagraphs(child, depth + 1)); return paragraphs; }
function tableCell(text: string, header = false) { return new TableCell({ shading: header ? { type: ShadingType.CLEAR, fill: 'E0E7FF' } : undefined, children: [new Paragraph({ children: [new TextRun({ text: text || ' ', bold: header })] })] }); }
export async function convertXmlToDocx(source: string, mode: XmlToWordMode, sourceName = 'document.xml'): Promise<ConversionResult> { const root = parseXml(source); const warnings: string[] = []; let children: Array<Paragraph | Table>; if (mode === 'raw') { const formatted = formatXml(source, { indentation: '  ', collapseContent: true, lineSeparator: '\n' }); children = [new Paragraph({ text: 'Formatted XML', heading: HeadingLevel.TITLE }), ...formatted.split('\n').map((line) => new Paragraph({ children: [new TextRun({ text: line || ' ', font: 'Courier New', size: 18 })], spacing: { after: 20 } }))]; } else if (mode === 'table') { const data = findRepeatedSiblingTable(root); if (!data) { warnings.push('No repeated sibling records were found, so the document uses readable hierarchy mode instead.'); children = hierarchyParagraphs(root); } else children = [new Paragraph({ text: data.title, heading: HeadingLevel.TITLE }), new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [new TableRow({ children: data.headers.map((header) => tableCell(header, true)), tableHeader: true }), ...data.rows.map((row) => new TableRow({ children: row.map((value) => tableCell(value)) }))], borders: { top: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' }, bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' }, left: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' }, right: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' }, insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: 'E2E8F0' }, insideVertical: { style: BorderStyle.SINGLE, size: 1, color: 'E2E8F0' } } })]; } else children = hierarchyParagraphs(root); const document = new Document({ creator: 'Navorika XML to Word Converter', title: root.name, description: 'DOCX generated locally from XML', styles: { default: { document: { run: { font: 'Arial', size: 22 }, paragraph: { spacing: { after: 120, line: 276 } } } } }, sections: [{ properties: {}, children }] }); return { blob: await Packer.toBlob(document), fileName: safeDownloadName(sourceName, 'docx'), warnings }; }
