import { XMLParser, XMLValidator } from 'fast-xml-parser';
import { XML_WORD_LIMITS } from './config';
import { assertSafeXmlSource, ConversionError } from './security';
import type { XmlTreeNode } from './types';
type OrderedEntry = Record<string, unknown> & { ':@'?: Record<string, unknown> };
function decodeSafeReferences(value: string) { return value.replace(/&#(?:x([0-9a-f]+)|([0-9]+));/gi, (match, hex: string | undefined, decimal: string | undefined) => { const codePoint = Number.parseInt(hex ?? decimal ?? '', hex ? 16 : 10); return Number.isInteger(codePoint) && codePoint >= 0 && codePoint <= 0x10ffff && !(codePoint >= 0xd800 && codePoint <= 0xdfff) ? String.fromCodePoint(codePoint) : match; }).replaceAll('&lt;', '<').replaceAll('&gt;', '>').replaceAll('&quot;', '"').replaceAll('&apos;', "'").replaceAll('&amp;', '&'); }
function entriesToNodes(entries: unknown[], state: { count: number }, depth = 1): XmlTreeNode[] { if (depth > XML_WORD_LIMITS.maxXmlDepth) throw new ConversionError(`XML nesting exceeds the safe depth limit of ${XML_WORD_LIMITS.maxXmlDepth}.`); const result: XmlTreeNode[] = []; for (const raw of entries) { if (!raw || typeof raw !== 'object') continue; const entry = raw as OrderedEntry; for (const [name, value] of Object.entries(entry)) { if (name === ':@' || name.startsWith('?') || name.startsWith('#')) continue; state.count += 1; if (state.count > XML_WORD_LIMITS.maxXmlNodes) throw new ConversionError(`XML contains more than ${XML_WORD_LIMITS.maxXmlNodes.toLocaleString()} elements.`); const content = Array.isArray(value) ? value as unknown[] : []; const text = decodeSafeReferences(content.flatMap((item) => { if (!item || typeof item !== 'object') return []; const textValue = (item as Record<string, unknown>)['#text']; return typeof textValue === 'string' ? [textValue] : []; }).join('').trim()); const attributes = Object.fromEntries(Object.entries(entry[':@'] ?? {}).map(([key, attr]) => [key.replace(/^@_/, ''), decodeSafeReferences(String(attr))])); result.push({ name, attributes, text, children: entriesToNodes(content, state, depth + 1) }); } } return result; }
export function parseXml(source: string): XmlTreeNode { assertSafeXmlSource(source); const validation = XMLValidator.validate(source, { allowBooleanAttributes: false }); if (validation !== true) { const line = validation.err.line ? ` at line ${validation.err.line}, column ${validation.err.col}` : ''; throw new ConversionError(`Malformed XML${line}: ${validation.err.msg}`); } const parser = new XMLParser({ preserveOrder: true, ignoreAttributes: false, attributeNamePrefix: '', trimValues: false, parseTagValue: false, parseAttributeValue: false, processEntities: false }); const roots = entriesToNodes(parser.parse(source) as unknown[], { count: 0 }); if (roots.length !== 1) throw new ConversionError('XML must contain exactly one root element.'); return roots[0]; }
export function escapeXml(value: string) { return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&apos;'); }
