'use client';

import { useState } from 'react';
import CorelFileDropzone from './CorelFileDropzone';
import { CorelError } from './CorelNotices';
import { detectCdrVersion } from '@/lib/converters/coreldraw/validation';
import { CORELDRAW_MAX_UPLOAD_BYTES } from '@/lib/converters/coreldraw/formats';

export default function CdrVersionChecker() { const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(''); const [info, setInfo] = useState<{ container: string; code: string; version: string; size: number } | null>(null); const choose = async (next: File) => { setError(''); setInfo(null); if (!/\.cdr$/i.test(next.name) || !next.size || next.size > CORELDRAW_MAX_UPLOAD_BYTES) { setFile(null); setError('Choose a non-empty .cdr file no larger than 15 MB.'); return; } try { const bytes = new Uint8Array(await next.slice(0, 64).arrayBuffer()); const detected = detectCdrVersion(bytes); setFile(next); setInfo({ ...detected, size: next.size }); } catch (cause) { setFile(null); setError(cause instanceof Error ? cause.message : 'The CDR header could not be read.'); } }; return <section className="mx-auto max-w-5xl space-y-5 rounded-3xl border border-slate-200 bg-white p-4 shadow-xl dark:border-slate-800 dark:bg-slate-900 sm:p-6"><p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200">Only the file header is read locally in your browser for this check; the CDR is not uploaded.</p><CorelFileDropzone accept=".cdr,application/vnd.corel-draw" file={file} label="Drop a CDR file to inspect its version" help="Header check only · maximum 15 MB" onFile={choose} />{error && <CorelError message={error} />}{info && <div aria-live="polite" className="grid gap-3 rounded-2xl border border-indigo-200 bg-indigo-50 p-5 dark:border-indigo-900 dark:bg-indigo-950/30 sm:grid-cols-2"><p><span className="block text-sm text-[var(--muted-foreground)]">Detected container</span><strong>{info.container}</strong></p><p><span className="block text-sm text-[var(--muted-foreground)]">Header code</span><strong>{info.code}</strong></p><p><span className="block text-sm text-[var(--muted-foreground)]">Likely version</span><strong>{info.version}</strong></p><p><span className="block text-sm text-[var(--muted-foreground)]">File size</span><strong>{(info.size / 1024).toFixed(1)} KB</strong></p></div>}<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-100"><strong>This is a version checker, not a version converter.</strong> Rewriting a newer CDR into an older native CDR version requires CorelDRAW or a verified CDR writer. Export to PDF/SVG for interchange, or ask the sender to use Save As in CorelDRAW.</div></section>; }
