import type { CorelServerConfig } from './CorelServerTool';

export const corelServerConfigs = {
  pdf: { kind: 'pdf-to-corel', inputFormats: ['pdf'], defaultOutput: 'svg', uploadLabel: 'Drop a PDF here', uploadHelp: 'PDF only · maximum 15 MB · SVG/EPS export uses the first page', showNativeNotice: true, outputChoices: [{ value: 'pdf', label: 'PDF — preserve all pages' }, { value: 'svg', label: 'SVG — editable first page', capability: 'pdfToSvg' }, { value: 'eps', label: 'EPS — print-ready first page', capability: 'pdfToEps' }] },
  word: { kind: 'word-to-corel', inputFormats: ['doc','docx'], defaultOutput: 'pdf', uploadLabel: 'Drop a Word document here', uploadHelp: 'DOC or DOCX · maximum 15 MB · fonts depend on server availability', showNativeNotice: true, requiredCapability: 'docxToPdf', outputChoices: [{ value: 'pdf', label: 'PDF — preserve layout' }, { value: 'svg', label: 'SVG — editable first page', capability: 'pdfToSvg' }, { value: 'eps', label: 'EPS — print-ready first page', capability: 'pdfToEps' }], modes: [{ value: 'preserve', label: 'Preserve layout', help: 'Best for forms, brochures, tables, and multiple pages.' }, { value: 'editable', label: 'Editable vector', help: 'Export the first page as SVG; text and curves can vary after import.' }, { value: 'print', label: 'Print ready', help: 'Use PDF or first-page EPS and verify fonts before printing.' }] },
  svg: { kind: 'svg-to-corel', inputFormats: ['svg'], defaultOutput: 'svg', uploadLabel: 'Drop an SVG here', uploadHelp: 'Safe SVG only · maximum 15 MB · active/external content is rejected', showNativeNotice: true, outputChoices: [{ value: 'svg', label: 'Validated SVG — preserve vectors/text' }, { value: 'pdf', label: 'PDF — CorelDRAW-ready layout', capability: 'docxToPdf' }, { value: 'eps', label: 'EPS — first-page print interchange', capability: 'pdfToEps' }] },
  ai: { kind: 'ai-to-corel', inputFormats: ['ai'], defaultOutput: 'pdf', uploadLabel: 'Drop an Adobe Illustrator file here', uploadHelp: 'PDF-compatible or PostScript AI · maximum 15 MB', showNativeNotice: true, requiredCapability: 'postscriptToPdf', outputChoices: [{ value: 'pdf', label: 'PDF — CorelDRAW-ready interchange' }, { value: 'svg', label: 'SVG — editable first page', capability: 'pdfToSvg' }, { value: 'eps', label: 'EPS — first-page interchange', capability: 'pdfToEps' }] },
  eps: { kind: 'eps-to-corel', inputFormats: ['eps'], defaultOutput: 'pdf', uploadLabel: 'Drop an EPS file here', uploadHelp: 'PostScript EPS · maximum 15 MB', showNativeNotice: true, requiredCapability: 'postscriptToPdf', outputChoices: [{ value: 'pdf', label: 'PDF — CorelDRAW-ready interchange' }, { value: 'svg', label: 'SVG — editable first page', capability: 'pdfToSvg' }, { value: 'eps', label: 'EPS — normalized first-page interchange' }] },
  viewer: { kind: 'cdr-viewer', inputFormats: ['cdr'], defaultOutput: 'pdf', uploadLabel: 'Drop a CDR file to preview', uploadHelp: 'RIFF- or ZIP-based CDR · maximum 15 MB', requiredCapability: 'cdrRead', viewer: true, outputChoices: [{ value: 'pdf', label: 'PDF preview — all readable pages' }, { value: 'svg', label: 'SVG preview — first page', capability: 'pdfToSvg' }, { value: 'png', label: 'PNG preview — first page' }] },
  cdrPdf: { kind: 'cdr-to-pdf', inputFormats: ['cdr'], defaultOutput: 'pdf', uploadLabel: 'Drop a CDR file here', uploadHelp: 'RIFF- or ZIP-based CDR · maximum 15 MB', requiredCapability: 'cdrRead', outputChoices: [{ value: 'pdf', label: 'PDF — preserve readable pages' }] },
  cdrSvg: { kind: 'cdr-to-svg', inputFormats: ['cdr'], defaultOutput: 'svg', uploadLabel: 'Drop a CDR file here', uploadHelp: 'First readable page exported to SVG · maximum 15 MB', requiredCapability: 'cdrRead', outputChoices: [{ value: 'svg', label: 'SVG — editable first page', capability: 'pdfToSvg' }] },
  cdrPng: { kind: 'cdr-to-png', inputFormats: ['cdr'], defaultOutput: 'png', uploadLabel: 'Drop a CDR file here', uploadHelp: 'First readable page exported to PNG · maximum 15 MB', requiredCapability: 'cdrRead', rasterControls: true, outputChoices: [{ value: 'png', label: 'PNG — first-page raster export' }] },
  cdrJpg: { kind: 'cdr-to-jpg', inputFormats: ['cdr'], defaultOutput: 'jpg', uploadLabel: 'Drop a CDR file here', uploadHelp: 'First readable page exported to JPG · maximum 15 MB', requiredCapability: 'cdrRead', rasterControls: true, outputChoices: [{ value: 'jpg', label: 'JPG — first-page raster export' }] },
  cdrEps: { kind: 'cdr-to-eps', inputFormats: ['cdr'], defaultOutput: 'eps', uploadLabel: 'Drop a CDR file here', uploadHelp: 'First readable page exported to EPS · maximum 15 MB', requiredCapability: 'cdrRead', outputChoices: [{ value: 'eps', label: 'EPS — first-page print interchange', capability: 'pdfToEps' }] },
} satisfies Record<string, CorelServerConfig>;
