const positive = (value:number,name:string) => { if(!Number.isFinite(value)||value<=0) throw new Error(`${name} must be greater than zero.`); return value };
export const withWaste=(value:number,waste:number)=>value*(1+Math.max(0,waste)/100);

export function roofPitch(rise:number,run:number,rafterRun?:number){positive(rise,'Rise');positive(run,'Run');const ratio=rise/run;return{pitch12:ratio*12,angle:Math.atan(ratio)*180/Math.PI,percent:ratio*100,multiplier:Math.sqrt(1+ratio**2),rafterLength:rafterRun&&rafterRun>0?rafterRun*Math.sqrt(1+ratio**2):null}}
export function stairs(totalRise:number,maxRiser:number,treadDepth:number,width?:number){positive(totalRise,'Total rise');positive(maxRiser,'Maximum riser');positive(treadDepth,'Tread depth');const risers=Math.ceil(totalRise/maxRiser);const actualRiser=totalRise/risers;const treads=Math.max(0,risers-1);const totalRun=treads*treadDepth;return{risers,actualRiser,treads,totalRun,stringerLength:Math.hypot(totalRise,totalRun),angle:Math.atan2(totalRise,totalRun)*180/Math.PI,stairArea:width&&width>0?totalRun*width:null}}
export function deckBoards(lengthFt:number,widthFt:number,boardWidthIn:number,boardLengthFt:number,gapIn:number,orientation:'length'|'width',waste:number){positive(lengthFt,'Deck length');positive(widthFt,'Deck width');positive(boardWidthIn,'Board width');positive(boardLengthFt,'Board length');if(gapIn<0)throw new Error('Gap cannot be negative.');const rowSpanFt=orientation==='length'?widthFt:lengthFt;const courseLengthFt=orientation==='length'?lengthFt:widthFt;const rows=Math.ceil((rowSpanFt*12+gapIn)/(boardWidthIn+gapIn));const piecesPerRow=Math.ceil(courseLengthFt/boardLengthFt);const base=rows*piecesPerRow;const required=Math.ceil(withWaste(base,waste));const linearFeet=required*boardLengthFt;const coverage=rows*boardWidthIn/12*courseLengthFt;return{rows,piecesPerRow,base,required,linearFeet,coverage,wasteBoards:required-base}}
export function fence(length:number,mode:'panel'|'spacing',sectionLength:number,corners:number,gates:number,gateWidth:number,waste:number,rails:number){positive(length,'Fence length');positive(sectionLength,'Panel length or post spacing');if([corners,gates,gateWidth,waste,rails].some(x=>x<0))throw new Error('Counts and allowances cannot be negative.');const net=Math.max(0,length-gates*gateWidth);const sections=Math.ceil(net/sectionLength);const panels=mode==='panel'?Math.ceil(withWaste(sections,waste)):0;const cornerEnd=Math.max(2,Math.floor(corners)+Math.floor(gates)*2);const linePosts=Math.max(0,sections+1-cornerEnd);return{net,sections,panels,posts:linePosts+cornerEnd,linePosts,cornerEnd,rails:Math.ceil(sections*rails)}}
export function postHoleConcrete(holeDiameterIn:number,depthIn:number,count:number,shape:'round'|'rectangle',postAIn:number,postBIn:number,bagYieldFt3:number){[holeDiameterIn,depthIn,count,postAIn,bagYieldFt3].forEach((x,i)=>positive(x,['Hole diameter','Depth','Count','Post size','Bag yield'][i]));if(shape==='rectangle')positive(postBIn,'Post width');const hole=Math.PI*(holeDiameterIn/24)**2*(depthIn/12);const displacement=shape==='round'?Math.PI*(postAIn/24)**2*(depthIn/12):(postAIn/12)*(postBIn/12)*(depthIn/12);const perHole=Math.max(0,hole-displacement);const ft3=perHole*Math.ceil(count);return{hole,displacement,perHole,ft3,yd3:ft3/27,bags:Math.ceil(ft3/bagYieldFt3)}}
export function drywall(area:number,ceiling:number,openings:number,sheetWidth:number,sheetHeight:number,waste:number){[area,sheetWidth,sheetHeight].forEach((x,i)=>positive(x,['Wall area','Sheet width','Sheet height'][i]));const net=Math.max(0,area+Math.max(0,ceiling)-Math.max(0,openings));const adjusted=withWaste(net,waste);const sheetArea=sheetWidth*sheetHeight;const base=Math.ceil(net/sheetArea),sheets=Math.ceil(adjusted/sheetArea);return{net,adjusted,base,sheets,wasteSheets:sheets-base,screws:Math.ceil(sheets*32),tapeFt:Math.ceil(net*0.27),compoundGallons:Math.ceil(net/450*10)/10}}
export function pavers(areaFt2:number,lengthIn:number,widthIn:number,waste:number,palletQuantity?:number){[areaFt2,lengthIn,widthIn].forEach((x,i)=>positive(x,['Area','Paver length','Paver width'][i]));const each=lengthIn*widthIn/144;const base=Math.ceil(areaFt2/each);const count=Math.ceil(withWaste(base,waste));return{areaFt2,each,base,count,wastePavers:count-base,pallets:palletQuantity&&palletQuantity>0?Math.ceil(count/palletQuantity):null}}
export function polymericSand(areaFt2:number,paverLengthIn:number,paverWidthIn:number,jointWidthIn:number,jointDepthIn:number,densityLbFt3:number,bagLb:number,waste:number){[areaFt2,paverLengthIn,paverWidthIn,jointWidthIn,jointDepthIn,densityLbFt3,bagLb].forEach((x,i)=>positive(x,['Area','Paver length','Paver width','Joint width','Joint depth','Density','Bag size'][i]));const paverArea=paverLengthIn*paverWidthIn;const count=areaFt2*144/paverArea;const jointLengthIn=count*(paverLengthIn+paverWidthIn);const volumeFt3=jointLengthIn*jointWidthIn*jointDepthIn/1728;const weight=withWaste(volumeFt3*densityLbFt3,waste);return{volumeFt3,weight,bags:Math.ceil(weight/bagLb)}}
export function landscapeVolume(areaFt2:number,depthIn:number){positive(areaFt2,'Area');positive(depthIn,'Depth');const ft3=areaFt2*depthIn/12;return{ft3,yd3:ft3/27,m3:ft3*0.0283168466,liters:ft3*28.3168466}}
