const finite = (value:number,name:string) => { if(!Number.isFinite(value)) throw new RangeError(`${name} must be a finite number.`); return value };
const positive = (value:number,name:string) => { finite(value,name); if(value<=0) throw new RangeError(`${name} must be greater than zero.`); return value };
const nonNegative = (value:number,name:string) => { finite(value,name); if(value<0) throw new RangeError(`${name} cannot be negative.`); return value };
export const withWaste=(value:number,waste:number)=>{nonNegative(value,'Base quantity');nonNegative(waste,'Waste allowance');return value*(1+waste/100)};
const ceilPurchase=(value:number)=>Math.ceil(value-Number.EPSILON*Math.max(1,Math.abs(value))*16);

export function roofPitch(rise:number,run:number,rafterRun?:number){positive(rise,'Rise');positive(run,'Run');const ratio=rise/run;return{pitch12:ratio*12,angle:Math.atan(ratio)*180/Math.PI,percent:ratio*100,multiplier:Math.sqrt(1+ratio**2),rafterLength:rafterRun&&rafterRun>0?rafterRun*Math.sqrt(1+ratio**2):null}}
export function stairs(totalRise:number,maxRiser:number,treadDepth:number,width?:number){positive(totalRise,'Total rise');positive(maxRiser,'Maximum riser');positive(treadDepth,'Tread depth');const risers=Math.ceil(totalRise/maxRiser);const actualRiser=totalRise/risers;const treads=Math.max(0,risers-1);const totalRun=treads*treadDepth;return{risers,actualRiser,treads,totalRun,stringerLength:Math.hypot(totalRise,totalRun),angle:Math.atan2(totalRise,totalRun)*180/Math.PI,stairArea:width&&width>0?totalRun*width:null}}
export function deckBoards(lengthFt:number,widthFt:number,boardWidthIn:number,boardLengthFt:number,gapIn:number,orientation:'length'|'width',waste:number){positive(lengthFt,'Deck length');positive(widthFt,'Deck width');positive(boardWidthIn,'Board width');positive(boardLengthFt,'Board length');nonNegative(gapIn,'Gap');nonNegative(waste,'Waste allowance');const rowSpanFt=orientation==='length'?widthFt:lengthFt;const courseLengthFt=orientation==='length'?lengthFt:widthFt;const rows=Math.ceil((rowSpanFt*12+gapIn)/(boardWidthIn+gapIn));const exactStockEquivalent=rows*courseLengthFt/boardLengthFt;const piecesPerRow=Math.ceil(courseLengthFt/boardLengthFt);const base=rows*piecesPerRow;const adjustedBoards=withWaste(base,waste);const required=Math.ceil(adjustedBoards);const linearFeet=required*boardLengthFt;const coverage=rows*boardWidthIn/12*courseLengthFt;return{rows,piecesPerRow,exactStockEquivalent,base,adjustedBoards,required,linearFeet,coverage,wasteBoards:required-base}}
export function fence(length:number,mode:'panel'|'spacing',sectionLength:number,corners:number,gates:number,gateWidth:number,waste:number,rails:number){positive(length,'Fence length');positive(sectionLength,'Panel length or post spacing');[corners,gates,gateWidth,waste,rails].forEach((x,i)=>nonNegative(x,['End/corner posts','Gates','Gate width','Waste allowance','Rails per section'][i]));const wholeGates=Math.floor(gates);const gateOpenings=wholeGates*gateWidth;if(gateOpenings>=length)throw new RangeError('Combined gate width must be less than total fence length.');const net=length-gateOpenings;const sections=Math.ceil(net/sectionLength);const adjustedPanels=mode==='panel'?withWaste(sections,waste):0;const panels=mode==='panel'?Math.ceil(adjustedPanels):0;const cornerEnd=Math.max(2,Math.floor(corners),wholeGates*2);const minimumRunPosts=sections+wholeGates+1;const posts=Math.max(minimumRunPosts,cornerEnd);const linePosts=Math.max(0,posts-cornerEnd);return{net,sections,adjustedPanels,panels,posts,linePosts,cornerEnd,rails:Math.ceil(sections*rails)}}
export function postHoleConcrete(holeDiameterIn:number,depthIn:number,count:number,shape:'round'|'rectangle',postAIn:number,postBIn:number,bagYieldFt3:number){[holeDiameterIn,depthIn,count,postAIn,bagYieldFt3].forEach((x,i)=>positive(x,['Hole diameter','Depth','Count','Post size','Bag yield'][i]));if(shape==='rectangle')positive(postBIn,'Post width');const hole=Math.PI*(holeDiameterIn/24)**2*(depthIn/12);const displacement=shape==='round'?Math.PI*(postAIn/24)**2*(depthIn/12):(postAIn/12)*(postBIn/12)*(depthIn/12);const perHole=Math.max(0,hole-displacement);const ft3=perHole*Math.ceil(count);return{hole,displacement,perHole,ft3,yd3:ft3/27,bags:Math.ceil(ft3/bagYieldFt3)}}
export function drywall(area:number,ceiling:number,openings:number,sheetWidth:number,sheetHeight:number,waste:number){[area,sheetWidth,sheetHeight].forEach((x,i)=>positive(x,['Wall area','Sheet width','Sheet height'][i]));nonNegative(ceiling,'Ceiling area');nonNegative(openings,'Openings area');nonNegative(waste,'Waste allowance');const gross=area+ceiling;if(openings>=gross)throw new RangeError('Openings area must be less than the combined wall and ceiling area.');const net=gross-openings;const adjusted=withWaste(net,waste);const sheetArea=sheetWidth*sheetHeight;const exactBaseSheets=net/sheetArea,exactAdjustedSheets=adjusted/sheetArea;const base=Math.ceil(exactBaseSheets),sheets=Math.ceil(exactAdjustedSheets);return{gross,net,adjusted,sheetArea,exactBaseSheets,exactAdjustedSheets,base,sheets,wasteSheets:sheets-base,screws:Math.ceil(sheets*32),tapeFt:Math.ceil(net*0.27),compoundGallons:Math.ceil(net/450*10)/10}}
export function pavers(areaFt2:number,lengthIn:number,widthIn:number,waste:number,palletQuantity?:number){[areaFt2,lengthIn,widthIn].forEach((x,i)=>positive(x,['Area','Paver length','Paver width'][i]));nonNegative(waste,'Waste allowance');const each=lengthIn*widthIn/144;const exactBase=areaFt2/each;const adjustedCount=withWaste(exactBase,waste);const base=ceilPurchase(exactBase);const count=ceilPurchase(adjustedCount);let pallets=null;if(palletQuantity!==undefined)pallets=ceilPurchase(count/positive(palletQuantity,'Pavers per pallet'));return{areaFt2,each,exactBase,adjustedCount,base,count,wastePavers:count-base,pallets}}
export function polymericSand(areaFt2:number,paverLengthIn:number,paverWidthIn:number,jointWidthIn:number,jointDepthIn:number,densityLbFt3:number,bagLb:number,waste:number){[areaFt2,paverLengthIn,paverWidthIn,jointWidthIn,jointDepthIn,densityLbFt3,bagLb].forEach((x,i)=>positive(x,['Area','Paver length','Paver width','Joint width','Joint depth','Density','Bag size'][i]));nonNegative(waste,'Waste allowance');const moduleAreaIn2=(paverLengthIn+jointWidthIn)*(paverWidthIn+jointWidthIn);const paverAreaIn2=paverLengthIn*paverWidthIn;const jointPlanAreaIn2=moduleAreaIn2-paverAreaIn2;const repeatModules=areaFt2*144/moduleAreaIn2;const volumeFt3=repeatModules*jointPlanAreaIn2*jointDepthIn/1728;const baseWeight=volumeFt3*densityLbFt3;const adjustedWeight=withWaste(baseWeight,waste);const exactBags=adjustedWeight/bagLb;return{moduleAreaIn2,jointPlanAreaIn2,repeatModules,volumeFt3,baseWeight,adjustedWeight,weight:adjustedWeight,exactBags,bags:Math.ceil(exactBags)}}
export function landscapeVolume(areaFt2:number,depthIn:number){positive(areaFt2,'Area');positive(depthIn,'Depth');const ft3=areaFt2*depthIn/12;return{ft3,yd3:ft3/27,m3:ft3*0.0283168466,liters:ft3*28.3168466}}
