'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import { AlertTriangle, TrendingUp, HeartPulse, Hammer, Wrench, ArrowLeft, ShieldAlert } from 'lucide-react';

export default function DisclaimerPage() {
  const lastUpdated = 'September 27, 2026';

  const sections = [
    {
      icon: <TrendingUp className="h-6 w-6 text-emerald-500" />,
      title: 'Financial & Investment Calculators',
      badge: 'Planning Estimates Only',
      badgeColor: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 border-emerald-500/20',
      content: 'Calculators in the financial category—including SIP returns, loan EMI, home loan amortization, income tax projections, compound interest, fixed deposits, and retirement planning—are provided strictly for general informational and educational scenario planning.',
      points: [
        'Not Financial Advice: Results generated by our calculators do not constitute financial, investment, legal, accounting, or tax advice.',
        'Market & Regulatory Variables: Investment returns and interest rates fluctuate over time. Inflation, statutory amendments, changing tax slabs, and administrative fees will impact actual financial outcomes.',
        'Independent Verification: Always consult with a certified financial planner, registered tax consultant, or licensed chartered accountant before making binding financial commitments.',
      ],
    },
    {
      icon: <HeartPulse className="h-6 w-6 text-rose-500" />,
      title: 'Health, Fitness & Biometrics Calculators',
      badge: 'Not Medical Advice',
      badgeColor: 'bg-rose-500/10 text-rose-700 dark:text-rose-300 border-rose-500/20',
      content: 'Tools in the health category—including Body Mass Index (BMI), Basal Metabolic Rate (BMR), Total Daily Energy Expenditure (TDEE), target heart rate zones, macronutrient breakdowns, and calorie deficit estimators—are based on established mathematical population models.',
      points: [
        'Screening Aids Only: These calculations are generalized statistical formulas intended solely for self-tracking and fitness education. They do not diagnose, treat, cure, or prevent any disease or medical condition.',
        'Individual Variation: Mathematical formulas cannot account for individual variations in muscle mass, bone density, metabolic genetics, pregnancy, prescription medication, or underlying medical conditions.',
        'Medical Consultation: Always consult a licensed medical doctor, registered dietitian, or qualified healthcare professional before undertaking calorie restriction, intensive exercise programs, or nutritional changes.',
      ],
    },
    {
      icon: <Hammer className="h-6 w-6 text-amber-500" />,
      title: 'Construction & Engineering Calculators',
      badge: 'Field Estimates Only',
      badgeColor: 'bg-amber-500/10 text-amber-700 dark:text-amber-300 border-amber-500/20',
      content: 'Construction takeoff and structural planning tools—such as roof pitch calculators, stair stringer dimensions, joist deflection estimators, concrete volume, sand/gravel quantities, and electrical wire size calculators—provide preliminary rule-of-thumb estimates.',
      points: [
        'Not Certified Engineering: Calculations do not substitute for stamped architectural drawings, certified structural calculations, or licensed engineering evaluations.',
        'Code Compliance: Building requirements vary by municipality and jurisdiction. All load-bearing spans, concrete mixes, electrical runs, and safety clearances must comply with local building codes (such as IBC, IRC, NEC, or local municipal bylaws).',
        'Material & Field Variances: Material waste, sub-base settling, compaction factors, lumber grade variances, and site topography must be independently verified by a licensed general contractor or structural engineer.',
      ],
    },
    {
      icon: <Wrench className="h-6 w-6 text-indigo-500" />,
      title: 'General Utilities & Document Tools',
      badge: 'As-Is Operation',
      badgeColor: 'bg-indigo-500/10 text-indigo-700 dark:text-indigo-300 border-indigo-500/20',
      content: 'Digital document editors, image converters, and developer formatters (including PDF merging/compression, SVG rasterization, JSON/YAML conversion, and regex testing) operate on an "as-is" and "as-available" basis.',
      points: [
        'Data Backups: While our client-side architecture processes files in local browser memory without uploading them to external servers, software operations can encounter unexpected browser tab crashes, memory limits, or canvas bounds.',
        'Backup Responsibility: Users are strictly advised to maintain independent original backup copies of all files, documents, and code prior to conversion or manipulation.',
        'Interchange Formats: Specific specialized tools (such as vector CorelDRAW converters) produce compatible open interchange formats (PDF, EPS, SVG) rather than native proprietary files, as disclosed on the relevant tool pages.',
      ],
    },
  ];

  return (
    <main className="min-h-screen bg-[var(--background)] text-[var(--foreground)] pt-24 pb-16">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-[var(--muted-foreground)] hover:text-[var(--foreground)] transition-colors mb-8"
        >
          <ArrowLeft className="h-4 w-4" /> Back to Home
        </Link>

        <div className="mb-12">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-3 rounded-2xl bg-amber-500/10 text-amber-600 dark:text-amber-400">
              <ShieldAlert className="h-8 w-8" />
            </div>
            <div>
              <h1 className="text-3xl sm:text-4xl font-black tracking-tight">Legal & Calculation Disclaimer</h1>
              <p className="text-[var(--muted-foreground)] mt-1">
                Last updated: {lastUpdated}
              </p>
            </div>
          </div>
          <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-amber-800 dark:text-amber-300 text-sm leading-relaxed">
            <AlertTriangle className="h-5 w-5 inline mr-2 align-text-bottom" />
            <span>
              All Navorika calculations, tools, and guides are provided for informational and educational purposes only. They are not professional advice.
            </span>
          </div>
        </div>

        <div className="space-y-8">
          {sections.map((section, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: index * 0.08 }}
              className="p-6 rounded-2xl bg-[var(--card)] border border-[var(--border)]"
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-3">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-xl bg-[var(--muted)]/50 shrink-0">
                    {section.icon}
                  </div>
                  <h2 className="text-xl font-bold">{section.title}</h2>
                </div>
                <span className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold border ${section.badgeColor} self-start sm:self-auto`}>
                  {section.badge}
                </span>
              </div>

              <p className="text-[var(--muted-foreground)] leading-relaxed mt-2">
                {section.content}
              </p>

              <div className="mt-4 pt-4 border-t border-[var(--border)] space-y-2">
                {section.points.map((pt, i) => (
                  <div key={i} className="flex items-start gap-2.5 text-sm text-[var(--muted-foreground)] leading-relaxed">
                    <span className="text-indigo-500 font-bold mt-0.5">•</span>
                    <span>{pt}</span>
                  </div>
                ))}
              </div>
            </motion.div>
          ))}
        </div>

        <div className="mt-12 p-6 rounded-2xl bg-[var(--card)] border border-[var(--border)] text-center text-sm text-[var(--muted-foreground)]">
          <p>
            For technical details on how our formulas and tools are validated, see our{' '}
            <Link href="/methodology" className="text-indigo-600 dark:text-indigo-400 font-medium hover:underline">
              Calculation Methodology
            </Link>
            . If you notice any calculation discrepancy, please contact{' '}
            <a href="mailto:admin@navorika.com" className="text-indigo-600 dark:text-indigo-400 font-medium hover:underline">
              admin@navorika.com
            </a>
            .
          </p>
        </div>
      </div>
    </main>
  );
}
